### ISSUE TITLE
Database: review sampling_relevant attributes

### ISSUE THREAD

**Issue by lmolkova** [open-telemetry/semantic-conventions#1019]
### Area(s)

area:db

### What happened?

We should identify and document attributes that are relevant for sampling

### Semantic convention version

1.25.0

**Comment by trask** [comment]
proposed list of sampling relevant attributes:

* `db.system`
* `db.namespace`
* `server.address`
* `server.port`
* `db.query.text` - (e.g. I want to filter out `SELECT 1` health checks)
* `db.collection.name` - yes
* `db.operation.name` - yes
* `db.query.parameter.<key>` - not sure about strong use case, but should be available at span start

**Comment by trask** [comment]
Note: `db.namespace` may not be available for sampling in Elasticsearch: https://github.com/open-telemetry/semantic-conventions/pull/1002/files#r1631347169

**Comment by lmolkova** [comment]
> db.query.text - (e.g. I want to filter out SELECT 1 health checks)

would mean sanitization for every query and the perf hit. I'd prefer to avoid it.

In the future, if we introduce some form of `db.query.alias` that one can be samplnig-relevant. 

It also feels like making attribute sampling-relevant post-stability should be ok - it adds a new feature without breaking anything existing. 
The [stability doc](https://github.com/open-telemetry/opentelemetry-specification/blob/9758cdddee20c699b620aac1d7f777ccd490f252/specification/versioning-and-stability.md?plain=1#L208
) can be interpreted in different ways though:

> Whether these attributes must be provided at span start time, due to sampling concerns.
