### ISSUE TITLE
New Azure Logs area

### ISSUE THREAD

**Issue by MikeGoldsmith** [open-telemetry/semantic-conventions#1027]
### Area(s)

area:new

### Is your change request related to a problem? Please describe.

As discussed in the following PR that contributes Azure logs transformations to the OpenTelemetry Collector Contrib, this issue proposes to add new semantic conventions for Azure Logs.
- https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/32486

### Describe the solution you'd like

New Azure Logs section for semantic conventions.

**Comment by joaopgrassi** [comment]
@MikeGoldsmith is this something you will be working on? Can I assign this to you then if so?
