### ISSUE TITLE
Add anchors to individual attributes in a markdown table 

### ISSUE THREAD

**Issue by AlexanderWert** [open-telemetry/semantic-conventions#1041]

**Comment by jsuereth** [comment]
Should be able to update:

- https://github.com/open-telemetry/semantic-conventions/blob/main/templates/registry/markdown/attribute_table.j2
- https://github.com/open-telemetry/semantic-conventions/blob/main/templates/registry/markdown/attribute_namespace.md.j2

I think the later is the important one, as it gives us the ability to anchor-link to the attribute registry.

**Comment by RichardChukwu** [comment]
Hello @jsuereth is the currently being worked on, or can I take it up please?
