### ISSUE TITLE
Adding token cost in to LLM Semantic Convention

### ISSUE THREAD

**Issue by gyliu513** [open-telemetry/semantic-conventions#1062]
### Area(s)

area:gen-ai

## Description

This is a legacy problem when we are working for the initial PR of GenAI Semantic Convention, we had some discussion before that we want to observability platform but not the instrumentation code to generate the cost value.

But here is a case that may not able to be covered: With a SaaS observability platform, if there are many customers using openai, there maybe some possibility that openai is providing different prices for different customers, with this case, the observability platform may not be a good place to calculate the price.

Can we take this as a common metrics and let instrumentation code to calculate this value? Thanks.

@nirga @lmolkova ^^ 

### Semantic convention version

nA

**Comment by lmolkova** [comment]
How would instrumentation code know the cost of token? 
It seems to be a service-side information instrumentation lib has no knowledge about.

**Comment by gyliu513** [comment]
@lmolkova how about setting some env variables when running instrumentation code? We can use the env variables to set the prices for input tokens and completion tokens, comments? Thanks

**Comment by lmolkova** [comment]
> @lmolkova how about setting some env variables when running instrumentation code? We can use the env variables to set the prices for input tokens and completion tokens, comments? Thanks

If the end user can add an env var, they can as well calculate the price at a query time. By adding metrics on the instrumentation side:
- we increase complexity of the instrumentation
- we increase the amount of data instrumentation reports
- we assume that price is static within the application which probably is not the case

But the result is the same - users use their knowledge about pricing to calculate things. 
Can you help me understand what are the benefits of instrumentation calculating this? 

In the perfect world this metric is reported by GenAI provider in some way, so I'd expect client metric will eventually be necessary only in edge cases.

**Comment by gyliu513** [comment]
thanks @lmolkova , this make sense, let me close this issue
