### ISSUE TITLE
Sustainability Semantic Convention Scope of work

### ISSUE THREAD

**Issue by Spazzy757** [open-telemetry/semantic-conventions#1080]
### Area(s)

area:new

### Is your change request related to a problem? Please describe.

With the introduction of various [European Laws regarding sustainability](https://www.consilium.europa.eu/en/policies/green-deal/fit-for-55-the-eu-plan-for-a-green-transition/), it is becoming increasingly more important for companies to track the emissions of their systems.

We have various efforts of implementations in the form of [Kepler](https://github.com/sustainable-computing-io/kepler) and others but creating conventions on tracking these metrics will be vital in order to align with other sectors and remove "creative accounting" practices in the IT sector

We want to have a unified metrics convention in order to better facilitate measuring sustainability metrics accross different ecosystems.

This Issue is to start discussing Scope of the SIG in order to better help us define the new Convention

### Describe the solution you'd like

We would like to start laying out a scope of work in the following [Google Doc](https://docs.google.com/document/d/1SlwMQm1zixXjTxZo-mYILJ4rL9--mLUpBuzXnKBJSDs/edit#heading=h.nncgosa3t0r1) in order to get together ideas on a sustainability focused convention

### Additional context

SIG createion PR: https://github.com/open-telemetry/community/pull/2018
Issue: https://github.com/open-telemetry/community/issues/2020

**Comment by danielgblanco** [comment]
@gabibeyer, @bertysentry, @nikimanoledaki, @mkorbi, @rossf7, @marceloamaral, @greenhsu123 as you've previously expressed your interest in joining this group, would you able to help with this?

Hopefully we can start to discuss this proposal in the next SIG meeting (Mondays at 15:00 BST)

**Comment by danielgblanco** [comment]
Closing as of https://github.com/open-telemetry/community/issues/2226
