### ISSUE TITLE
Should `server.address` and `server.port` be changed from required to recommended on SERVER spans?

### ISSUE THREAD

**Issue by trask** [open-telemetry/semantic-conventions#111]
Spinning this out from #109 as a separate issue.

Summarizing the discussion:

Pro: `server.address` and `server.port` are interesting, but not essential on SERVER telemetry for the tracing experience (because you can typically get similar identification of the service from `service.name`)
Con: being able to reconstruct url on server telemetry is useful
Pro: reconstructing url is not reliable since `server.address` and `server.port` typically come from `Host` header

**Comment by trask** [comment]
Another pro: HTTP/1.0 doesn't require `Host` header, so may not be able to populate `server.address`/`server.port`(?)

**Comment by lmolkova** [comment]
My argument on `recommended` is the following:

the difference between `required` and `recommended` is the ability to opt out. 
If we believe `server.address` and `server.port` are not quite useful in certain cases, we should let users opt-out.

In absence of `server.address`,  things that need to reconstruct the URL can fall back to `host.name` or `service.name` resource attributes.
