### ISSUE TITLE
k8s: new attributes: CSI driver and volume handle

### ISSUE THREAD

**Issue by gdvalle** [open-telemetry/semantic-conventions#1119]
### Area(s)

Semantic convention for otelcol's kubeletstatsreceiver, `area:k8s`.

### Is your change request related to a problem? Please describe.

In k8s, I would like to record CSI driver and volume handle information for relevant Persistent Volume Claims (PVCs) to be able to associate metrics to underlying disks.

### Describe the solution you'd like

Two new attributes, with each mapping 1:1 to the respective driver/volumeHandle fields in [CSIPersistentVolumeSource](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.27/#csipersistentvolumesource-v1-core):

* `csi.driver`
* `csi.volume.handle`

And a new value for the `k8s.volume.type` attribute, `csiPersistentVolume`.

### Describe alternatives you've considered

None

### Additional context

This grew from https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/32055

**Comment by ChrsMark** [comment]
There is no semantic convention for the `k8s.volume.type`. https://github.com/open-telemetry/semantic-conventions/issues/1164 will add this.

**Comment by mx-psi** [comment]
I removed this from the system semantic conventions WG since this WG does not handle Kubernetes-related semantic conventions
