### ISSUE TITLE
Should process.cpu.utilization and system.cpu.utilization be opt-in?

### ISSUE THREAD

**Issue by ChrsMark** [open-telemetry/semantic-conventions#1130]
### Area(s)

area:system

### Is your change request related to a problem? Please describe.

Following up from https://github.com/open-telemetry/semantic-conventions/issues/647#issuecomment-2152625724 we should decide on the requirement level for the [`process.cpu.utilization`](https://github.com/open-telemetry/semantic-conventions/blob/v1.26.0/docs/system/process-metrics.md#metric-processcpuutilization) and [`system.cpu.utilization`](https://github.com/open-telemetry/semantic-conventions/blob/v1.26.0/docs/system/system-metrics.md#metric-systemcpuutilization). At the moment these are `recommended` metrics but maybe we can consider if those can be `opt-in` since both of them can be calculated from their respective `*.cpu.time` metric.

[JVM metrics](https://github.com/open-telemetry/semantic-conventions/blob/v1.26.0/docs/runtime/jvm-metrics.md#metric-jvmcpurecent_utilization) define the `jvm.cpu.recent_utilization` as `recommended` however reading its description I'm not sure if that one can be derived from the [jvm.cpu.time](https://github.com/open-telemetry/semantic-conventions/blob/main/docs/runtime/jvm-metrics.md#metric-jvmcputime), so that might be a different case.

/cc @open-telemetry/semconv-system-approvers @braydonk @open-telemetry/semconv-jvm-approvers 

### Describe the solution you'd like

Having an alignment (if possible) on the requirement level for the `*.cpu.utilization` metrics across SemConv.

**Comment by mx-psi** [comment]
I support making them opt-in

**Comment by trask** [comment]
there was a semi-related discussion a while back:

https://github.com/open-telemetry/opentelemetry-specification/pull/2392#discussion_r833018035

> We had the same debate for `system.cpu.utilization` and the result of the discussion is that `system.cpu.utilization` was simpler for some backends than calculating from two metrics.

**Comment by ChrsMark** [comment]
I have mixed feelings about this tbh.
I would feel better to make those `opt-in` if we had `system.cpu.usage` and `process.cpu.usage` metrics (marked as recommended) to provide the deltas out of the box. Then the actual triangle is `cpu.usage`-`cpu.utilization`-`cpu.count` where we can standardize the `cpu.usage` and `cpu.count` while leave the `cpu.utilization` as `opt-in`.

@open-telemetry/semconv-system-approvers any thoughts on this?

**Comment by braydonk** [comment]
@ChrsMark could you clarify what `cpu.usage` is? There is already `cpu.time` which can be used along with `cpu.count` to get a percentage for `cpu.utilization`. I'm not sure what `cpu.usage` is representing in this scenario.

**Comment by ChrsMark** [comment]
> @ChrsMark could you clarify what `cpu.usage` is? There is already `cpu.time` which can be used along with `cpu.count` to get a percentage for `cpu.utilization`. I'm not sure what `cpu.usage` is representing in this scenario.

Please check me on this but I'm referring to the delta metric that we can calculate from the cumulative `cpu.time`. As it's also explained at https://github.com/open-telemetry/opentelemetry-specification/pull/2392#discussion_r833018035 it is:

```
cpu.usage = (cpu.time 2 - cpu.time 1) / (Timestamp 2 - Timestamp 1)
```
Where dividing this by `cpu.count` gives you the `cpu.utilization`.

My point point here is to ensure consistency with other metrics like the container's ones: https://github.com/open-telemetry/semantic-conventions/pull/1128

However at https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/c4bee406f5db233a2bc7f0c69185764fea9fb033/receiver/hostmetricsreceiver/internal/scraper/cpuscraper/ucal/cpu_utilization_calculator.go#L54 I see we don't really divide by the `cpu.count` 🤔  so I wonder if I miss anything here.

**Comment by dmitryax** [comment]
I support this. Thanks @ChrsMark!

**Comment by ChrsMark** [comment]
> However at https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/c4bee406f5db233a2bc7f0c69185764fea9fb033/receiver/hostmetricsreceiver/internal/scraper/cpuscraper/ucal/cpu_utilization_calculator.go#L54 I see we don't really divide by the cpu.count 🤔 so I wonder if I miss anything here.

We discussed that during today's SIG meeting (1st Aug 2024). Since we report this per core that's why we don't divide by the number of cores (it's actually a division by `1`). The correct aggregation for the total `cpu.utilization` would be the `avg`.

For processes it's also calculated properly. Divided by number of cores: https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/c4bee406f5db233a2bc7f0c69185764fea9fb033/receiver/hostmetricsreceiver/internal/scraper/processscraper/ucal/cpu_utilization_calculator.go#L60-L65

Hence, we are consistent here with other ares like k8s/containers.
We can proceed with switching to `opt-in` here. I will file a PR for this.

**Comment by braydonk** [comment]
Thanks for the info. I support as well, thanks!

**Comment by ChrsMark** [comment]
PR raised: https://github.com/open-telemetry/semantic-conventions/pull/1308
