### ISSUE TITLE
Unify  `system.cpu.state`, `process.cpu.state`, `container.cpu.state` into `cpu.mode`?

### ISSUE THREAD

**Issue by lmolkova** [open-telemetry/semantic-conventions#1139]
## `process.cpu.state` 

| Attribute           | Type   | Description                   | Examples                 | Stability                                                        |
| ------------------- | ------ | ----------------------------- | ------------------------ | ---------------------------------------------------------------- |
| `process.cpu.state` | string | The CPU state of the process. | `system`; `user`; `wait` | ![Experimental](https://img.shields.io/badge/-experimental-blue) |

`process.cpu.state` has the following list of well-known values. If one of them applies, then the respective value MUST be used; otherwise, a custom value MAY be used.

| Value    | Description | Stability                                                        |
| -------- | ----------- | ---------------------------------------------------------------- |
| `system` | system      | ![Experimental](https://img.shields.io/badge/-experimental-blue) |
| `user`   | user        | ![Experimental](https://img.shields.io/badge/-experimental-blue) |
| `wait`   | wait        | ![Experimental](https://img.shields.io/badge/-experimental-blue) |

## `system.cpu.state` 

| Attribute                   | Type   | Description                     | Examples            | Stability                                                        |
| --------------------------- | ------ | ------------------------------- | ------------------- | ---------------------------------------------------------------- |
| `system.cpu.state`          | string | The state of the CPU            | `idle`; `interrupt` | ![Experimental](https://img.shields.io/badge/-experimental-blue) |

`system.cpu.state` has the following list of well-known values. If one of them applies, then the respective value MUST be used; otherwise, a custom value MAY be used.

| Value       | Description | Stability                                                        |
| ----------- | ----------- | ---------------------------------------------------------------- |
| `idle`      | idle        | ![Experimental](https://img.shields.io/badge/-experimental-blue) |
| `interrupt` | interrupt   | ![Experimental](https://img.shields.io/badge/-experimental-blue) |
| `iowait`    | iowait      | ![Experimental](https://img.shields.io/badge/-experimental-blue) |
| `nice`      | nice        | ![Experimental](https://img.shields.io/badge/-experimental-blue) |
| `steal`     | steal       | ![Experimental](https://img.shields.io/badge/-experimental-blue) |
| `system`    | system      | ![Experimental](https://img.shields.io/badge/-experimental-blue) |
| `user`      | user        | ![Experimental](https://img.shields.io/badge/-experimental-blue) |

## Could we unify them?

It could also be useful on runtime-specific metrics:  https://github.com/open-telemetry/semantic-conventions/pull/1035#discussion_r1630687882

## `cpu.mode` 

| Attribute                   | Type   | Description                     | Examples            | Stability                                                        |
| --------------------------- | ------ | ------------------------------- | ------------------- | ---------------------------------------------------------------- |
| `cpu.mode`          | string | The state of the CPU            | `idle`; `interrupt` | ![Experimental](https://img.shields.io/badge/-experimental-blue) |

`cpu.mode` has the following list of well-known values. If one of them applies, then the respective value MUST be used; otherwise, a custom value MAY be used.

| Value       | Description | Stability                                                        |
| ----------- | ----------- | ---------------------------------------------------------------- |
| `user`      | user        | ![Experimental](https://img.shields.io/badge/-experimental-blue) |

Only `user` because it seems to be the most common denominator. But effectively:
- the general definition does not specify a full list (does not have to specify anything)
- `process`, `system`, `container`, `{runtime-specific}` semconv can document applicable values

**Comment by lmolkova** [comment]
Also

| Attribute                      | Type     | Description                                                                                                                                                                                                                                                             | Examples                                                                                                                                                                                                    | Stability                                                        |
| ------------------------------ | -------- | ----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- | ----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- | ---------------------------------------------------------------- |
| `container.cpu.state`          | string   | The CPU state for this data point.                                                                                                                                                                                                                                      | `user`; `kernel`                                                                                                                                                                                            | ![Experimental](https://img.shields.io/badge/-experimental-blue) |

`container.cpu.state` has the following list of well-known values. If one of them applies, then the respective value MUST be used; otherwise, a custom value MAY be used.

| Value    | Description                                                                                                     | Stability                                                        |
| -------- | --------------------------------------------------------------------------------------------------------------- | ---------------------------------------------------------------- |
| `kernel` | When tasks of the cgroup are in kernel mode (Linux). When all container processes are in kernel mode (Windows). | ![Experimental](https://img.shields.io/badge/-experimental-blue) |
| `system` | When CPU is used by the system (host OS)                                                                        | ![Experimental](https://img.shields.io/badge/-experimental-blue) |
| `user`   | When tasks of the cgroup are in user mode (Linux). When all container processes are in user mode (Windows).     | ![Experimental](https://img.shields.io/badge/-experimental-blue) |

**Comment by ChrsMark** [comment]
We have been evaluating this already at https://github.com/open-telemetry/semantic-conventions/pull/1026 ([issue](https://github.com/open-telemetry/semantic-conventions/issues/840)) which currently blocked at https://github.com/open-telemetry/semantic-conventions/pull/1026#discussion_r1620879719.

Any particular reason for having `.*mode` instead of `.state`? I guess that would be another major breaking change for `system` and `process` metrics at least.
/cc @open-telemetry/semconv-container-approvers @braydonk

**Comment by lmolkova** [comment]
> We have been evaluating this already at https://github.com/open-telemetry/semantic-conventions/pull/1026 (https://github.com/open-telemetry/semantic-conventions/issues/840) which currently blocked at https://github.com/open-telemetry/semantic-conventions/pull/1026#discussion_r1620879719.

Thanks! 

> Any particular reason for having .*mode instead of .state? 

No strong opinion, same concern as in https://github.com/open-telemetry/semantic-conventions/pull/1128#discussion_r1633597135

> I feel like state normally implies the ability to transition between different values which isn't true here.

CPU state and CPU mode seem to be both used widely, but CPU mode would probably be more precise? (i.e. someone looking at the `cpu.state` without the context might expect `failed`, `broken`, etc there. `state.mode` would not have such a problem)

Also this (but we should all take it with a grain of salt)

<img width="659" alt="image" src="https://github.com/open-telemetry/semantic-conventions/assets/2347409/1a039a40-2623-4b0d-9641-627d4f4785ed">

> I guess that would be another major breaking change for system and process metrics at least.

They are still experimental. Also if we are renaming them anyway, let's consider changing state to mode as well.

**Comment by lmolkova** [comment]
I'm going to close this as duplicate. Let's continue the discussion on https://github.com/open-telemetry/semantic-conventions/pull/1026/files#r1635136959
