### ISSUE TITLE
Request: add @braydonk in System Metrics approvers

### ISSUE THREAD

**Issue by ChrsMark** [open-telemetry/semantic-conventions#1153]
I would like to nominate @braydonk as System Metrics approver (@open-telemetry/semconv-system-approvers).
Braydon [has been working with the System Metrics stability group since the beginning](https://docs.google.com/document/d/1p5TH57t43XpxA48onLzX4PIr3g6ydYKCtR_AUlsCnQk/edit) while also being a codeowner for the [hostmetricsreceiver](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/receiver/hostmetricsreceiver/README.md) helping on bridging the gap between SemConv and the Collector.

cc: @mx-psi @dmitryax @jsuereth @open-telemetry/semconv-system-approvers @open-telemetry/specs-semconv-approvers @open-telemetry/specs-semconv-maintainers

**Comment by mx-psi** [comment]
I support

**Comment by dmitryax** [comment]
I support!

**Comment by lmolkova** [comment]
Done!

**Comment by braydonk** [comment]
Thanks!
