### ISSUE TITLE
Should `messaging.kafka.message.offset` be in the message namespace?

### ISSUE THREAD

**Issue by lmolkova** [open-telemetry/semantic-conventions#1156]
Kafka settlement is offset-based. 

When reporting settlement, we'd want to include `messaging.kafka.message.offset` on the settlement span as shown in https://github.com/open-telemetry/semantic-conventions/pull/1155. But that span does not have to be reported per message (it can be done in the background periodically, for each 1000th message, etc). 

It looks weird to have the offset attribute in the message namespace as it's not just a message property, but also a thing on its own. Someone may also want to create a metric for the offset (e.g. latest published offset vs latest consumed offset would show the size of the queue). In this case it's rather a  property of the topic/consumer group.

Suggesting `messaging.kafka.offset` or even a more generic one `messaging.offset`  since offset concept is popular in messaging world.

**Comment by pyohannes** [comment]
I'm in favor of making this a generic attribute (outside the `kafka` namespace).

I have no strong opinion whether it should be `messaging.offset` or `messaging.message.offset`. I'd have a slight preference for `messaging.offset` because it's shorter.

**Comment by lmolkova** [comment]
Related: #1036

**Comment by lmolkova** [comment]
Did some research on the terminology used by different messaging systems:

## Systems that use offset

- [Kafka](https://docs.confluent.io/platform/current/clients/consumer.html#concepts).
   - ✅  uses it in documentation
   - ✅  exposes in public APIs
   - ✅  uses it as a settlement mechanism
- [Azure Event Hubs](https://learn.microsoft.com/en-us/azure/event-hubs/event-hubs-features#stream-offsets).
   - ✅  uses it in documentation
   - ✅  exposes in public APIs
   - ✅  uses it as a settlement mechanism
- [Azure Service Bus](https://learn.microsoft.com/en-us/azure/service-bus-messaging/service-bus-queues-topics-subscriptions).
   - ❌ does not have a notion of offset. 
   - has a notion of sequence number
   - uses lock tokens to settle messages
- [Apache RocketMQ](https://rocketmq.apache.org/docs/featureBehavior/09consumerprogress/#working-mechanism)
   - ✅  uses it in documentation
   - ❌ does not expose it in public APIs
   - ❌ does not use it as a settlement mechanism (uses receipt handles)
- [RabbitMQ Streams](https://www.rabbitmq.com/docs/streams), not queues
   - ✅  uses it in documentation
   - 🟨  exposes it as a message property `message.properties.headers["x-stream-offset"]`
   - ❌ does not use it as a settlement mechanism (uses delivery tags)
- [AWS SQS](https://docs.aws.amazon.com/AWSSimpleQueueService/latest/SQSDeveloperGuide/sqs-queue-message-identifiers.html)
   - ❌ does not have a notion of offset or sequence number 
   - uses receipt handle to settle messages
- AWS SNS 
   - ❌ does not have a notion of offset or sequence number 
- GCP Pub/Sub
   - ❌ does not have a notion of offset or sequence number 
   - uses ack_id to settle
- Apache Pulsar 
   - ❌ does not have a notion of offset
   - [has sequence number](https://pulsar.apache.org/docs/3.3.x/concepts-messaging/#messages)
   - uses message id to settle
- Nats.io
   - ❌ does not have a notion of offset
   - has sequence number 
   - settles with reply_to

**Comment by lmolkova** [comment]
Based on this, I would prefer `messaging.kafka.offset`, (future) `messaging.eventhubs.offset`, (if needed) `messaging.rabbitmq.offset`

**Comment by pyohannes** [comment]
Discussed in the workgroup meeting, we will go with the proposal from @lmolkova in the previous comment.
