### ISSUE TITLE
Add k8s.volume.type attribute

### ISSUE THREAD

**Issue by ChrsMark** [open-telemetry/semantic-conventions#1164]
### Area(s)

area:k8s

### Is your change request related to a problem? Please describe.

`kubeletstats` receiver provides support for adding the `k8s.volume.type` attribute along with the volume related metrics: https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/v0.102.0/receiver/kubeletstatsreceiver/internal/kubelet/conventions.go#L7.

### Describe the solution you'd like

We need to define a Semantic Convention for this attribute.

### Additional context

Related to https://github.com/open-telemetry/semantic-conventions/issues/1119 and https://github.com/open-telemetry/semantic-conventions/issues/1032.

/cc @open-telemetry/semconv-k8s-approvers

**Comment by TylerHelmuth** [comment]
This attribute has been in use for a long time successfully, officially merging it here makes sense to me

**Comment by joaopgrassi** [comment]
@ChrsMark will you take this? Should I move to the system semconv project board?

**Comment by ChrsMark** [comment]
@joaopgrassi I can assign this to me and work on it in the near future unless there is anybody else willing to pick it up earlier.

This does not fall into the system semconv project. The System Metrics WG only focuses on host/system metrics and attributes.
This can be tracked by https://github.com/open-telemetry/semantic-conventions/issues/1032 until we form a K8s WG, hopefully some time soon :).
