### ISSUE TITLE
Messaging: per-message tracing when sending batches

### ISSUE THREAD

**Issue by lmolkova** [open-telemetry/semantic-conventions#1187]
In Messaging Instrumentation WG, we're looking for the proper way to trace multiple messages sent within a single batch.
We do not have a concept for this in tracing spec and want to hear opinions on the options we came up with.

E.g. a user sends a batch of messages like `producer.send([msg1, msg2])`, then this batch is reshuffled on the broker and then each message is sent to consumer(s) as a part of another batch. 

In this case, users should still be able to trace individual messages through the system. To achieve it, **we need a unique context per message** that's propagated from producer to consumer.

**Options**:
1. **Span per message**: `send` span has links to each message span.
    - Pros: fits into a current mental model
    - Cons: 
      - span duration is artificial: it's either 0 (message creation) or tight to `send` span duration. It can potentially measure when each message is sent (but many systems get ack on batch, not per message)
      -  extra span collection with corresponding perf hit and storage costs increase
      -  [EDIT]: Can't change this choice later in non-breaking manner
  <img width="356" alt="image" src="https://user-images.githubusercontent.com/2347409/182904830-88b7ac77-1763-4efe-9c39-1c8fcfea10ee.png">

2. **Spanless context**. Only create a new span context per message. `send` span has links to each message span context. 
    - Pros: 
      - no extra costs for span creation. all necessary information will go through links
      - [EDIT]: can report span (or event with context semantics) later in the future versions of the spec if spanless context will be proven difficult to use. This won't be breaking.
    - Cons:  
      - new mental model. There is a context with no span ever created
      - maybe more complicated indexing for links on the backends. I.e. there will be a link from the producer and a link from the consumer to the spanless context 

<img width="382" alt="image" src="https://user-images.githubusercontent.com/2347409/182904900-4f33275d-0551-4d23-9dc6-cdd5678dedf3.png">

More context: https://docs.google.com/document/d/1OrHsepd6GjzXKll1ggZyx1jBQd0d_t8NZXT1ZOem7D0/edit#heading=h.hfmrnf56kiuf

**Comment by lmolkova** [comment]
Reopening based on the feedback from @tedsuo to discuss zero-duration spans. Will bring it up on messaging SIG 6/27

**Comment by lmolkova** [comment]
capturing some feedback points:
- zero-duration spans smell - they should probably be events
- link to context is valid (even if there is no span)
- links that point to nothing should have timestamp and a name

**Comment by lmolkova** [comment]
Discussed at messaging SIG:
- spanless context is still controversial: there is a worry that it'd break backends
- we're losing more than timestamp and name - we're loosing causality - the link does not record the parent of the context. e.g.
  - Incoming HTTP request had `traceId1`  `spanId1`
  - Message created in scope of it had `traceId1`, `spanId2`
    - if we recorded a span, we'd record that parent of message is `spanId1`
    - **without the span we have no means to record that `spanId2` is a child of `spanId1`**
- are there other similar cases where we need the new context but not a new span?

We should look for more options:
1. Inject parent context into messages. 
   - Cons: can't distinguish messages that were created in the same context. 
2. Legalize (explain) zero-duration spans. Span is more than duration/status. It's context, causality, name, timestamp.
3. Evolve event/link combination. 
    - Pros:  event (with parent context) that has a secondary context describes a single point in time when the message was created.
    - Cons: this is effectively a new signal (links expressed as events)

Will wring it up on spec meeting.

**Comment by trask** [comment]
> Evolve event/link combination.
> Pros: event (with parent context) that has a secondary context (new message) describes a single point in time when the message was created.

I'm probably missing something here, how do you find the parent of the "new message" context?

**Comment by lmolkova** [comment]
> I'm probably missing something here, how do you find the parent of the "new message" context?

<img width="1141" alt="image" src="https://github.com/open-telemetry/semantic-conventions/assets/2347409/e8fb21af-d23f-4987-a627-3e66808e1827">

I think event is an unfortunate term - we don't want to build it on top of span events, but it's not a log (no payload).

This thing is a link detached from the span. It has
- parent context
- it's own unique span id
- name
- timestamp
- attributes

I.e. from the data structure it's a lightweight span without status, duration, links, or events.

**Comment by joaopgrassi** [comment]
@lmolkova given we have the conventions now mentioning the create context and IIRC "zero duration" spans are not a big deal, do we have anything left to do in this issue? It seems to me all is "resolved" now? Or am I missing something?

**Comment by lmolkova** [comment]
yeah,  I think we can close it - we have https://github.com/open-telemetry/semantic-conventions/issues/1273 to track remaining work (making per-message tracing disableable). Thanks!
