### ISSUE TITLE
Global uniqueness of service.name and service.namespace in the face of deployment.environment

### ISSUE THREAD

**Issue by bripkens** [open-telemetry/semantic-conventions#119]
Hey folks,

we are currently discussing the correct usage of `service.namespace` and `deployment.environment`, especially considering the uniqueness aspects that are called out within [service_experimental.yaml](https://github.com/open-telemetry/semantic-conventions/blob/main/semantic_conventions/resource/service_experimental.yaml). I have been digging through GitHub issues, PRs and the OTel demo, and I need help finding an answer.

Would it be correct or wrong to assume that the following is the intended usage of these attributes (in the face of missing `service.instance.id` attributes)?

Resource A:
 - `service.name=shoppingcart`
 - `service.namespace=opentelemetry-demo`
 - `deployment.environment=prod`

Resource B:
 - `service.name=shoppingcart`
 - `service.namespace=opentelemetry-demo`
 - `deployment.environment=dev`

Specific questions around this:

 1. Would this satisfy the uniqueness constraints [within the notes](https://github.com/open-telemetry/semantic-conventions/blob/bef5a68c2f580e48334bfb2a118345808b2e2125/semantic_conventions/resource/service_experimental.yaml#LL15C11-L17C92) of the `service.namespace` attribute?
 2. Should this constitute two separate services or a single one?

Thank you for your help.

**Comment by Oberon00** [comment]
I think this is not formally defined, but I would say that deployment.environment is not part of the service identity, but an informational attribute that tells you whether the service (which is uniquely identified by service.name + service.namespace) is in prod or dev.

Hence different service.instance.ids with same name + namespace should really be just different instances of the same service configuration.

You should probably have separate names or namespaces for services in different deployment.environments.

**Comment by bripkens** [comment]
> You should probably have separate names or namespaces for services in different deployment.environments.

So according to this, my example should be changed to something like the following:

Resource A:
 - `service.name=shoppingcart`
 - `service.namespace=prod-opentelemetry-demo`
 - `deployment.environment=prod`

Resource B:
 - `service.name=shoppingcart`
 - `service.namespace=dev-opentelemetry-demo`
 - `deployment.environment=dev`

IMHO we should call this out explicitly in the docs and with more examples / dos / don'ts. WDYT?

**Comment by deka** [comment]
@Oberon00 , you say
> You should probably have separate names or namespaces for services in different deployment.environments.  

In my case, I need to identify a service by its functional aspect. Whether it's in `dev` or `staging`, the result is the same (from a business point of view).  

Is there a missing notion to identify a service ?
`service.name` is `Logical name of the service`. Is `service.namespace` logical namespace ? 
in this case, adding the environment doesn't make sense for me.  

A priori, service.name + service.namespace is the only way to achieve 'logical' uniqueness.
Maybe you need a logical `id` or a `scopes` (with multiple values ? `dev,prod` or `sales,logistic,referential` ...).

**Comment by Oberon00** [comment]
I think the namespace can be used as exactly this scope that you want. Otherwise, maybe you should also have separate monitoring environments for your different monitored environments. Or maybe you are fine with prod and dev ending up in the same service (unlikely)
