### ISSUE TITLE
Could we remove `tls.client.server_name` in favor of `server.address`

### ISSUE THREAD

**Issue by lmolkova** [open-telemetry/semantic-conventions#1211]
`tls.client.server_name` is defined as 
https://github.com/open-telemetry/semantic-conventions/blob/5971366ae2fcaf2d01b1a52da92e872b7df5491d/docs/attributes-registry/tls.md?plain=1#L25

This should be the same as `server.address`. See https://community.f5.com/kb/technicalarticles/ssl-profiles-part-7-server-name-indication/279829

So the proposal is to deprecate the `tls.client.server_name` attribute.

**Comment by joaopgrassi** [comment]
CC @svrnm

**Comment by svrnm** [comment]
When I added this originally I took most attributes from Elastic Common Schema, so I had no other reason than that for adding it. 

+1 for deprecation
