### ISSUE TITLE
Should OS-specific metrics be in `system.{os}` or `{os}` namespace

### ISSUE THREAD

**Issue by lmolkova** [open-telemetry/semantic-conventions#1255]
>   currently both of these namespaces are used in this PR:
>
> * `linux.*`
> * and `system.linux.*`
>
> should we rename `system.linux.*` to `linux.*`?
>
> that would seem to align with our decision to move `process.runtime.jvm.*` to `jvm.*`

_Originally posted by @trask in https://github.com/open-telemetry/semantic-conventions/pull/1078#discussion_r1638375208_

**Comment by mx-psi** [comment]
@lmolkova Is this a duplicate of #1403?

**Comment by lmolkova** [comment]
Based on the recent discussion - https://github.com/open-telemetry/semantic-conventions/pull/1364#discussion_r1852465994, I believe we're leaning towards `system.{os}`. I'm going to close it since it should be addressed in #1403
