### ISSUE TITLE
Define attributes to identify a CPU

### ISSUE THREAD

**Issue by mx-psi** [open-telemetry/semantic-conventions#130]
CPUs allow users to fetch some identifying information about them. Similar to other system-level information such as the `os.version`, the `host.arch` or the kernel attributes proposed on #66, it can be helpful to have these kinds of attributes as part of the resource on OTLP payloads to identify and troubleshoot issues specific to a certain CPU model or its firmware version.

Many such identifying attributes can be found on Linux systems under the `/proc/cpuinfo` file. This issue would aim to identify the most important among them and create semantic conventions for them. In particular, at a minimum it seems like the following would be widely useful:
- CPU Vendor ID (see [CPUID](https://en.wikipedia.org/wiki/CPUID))
- CPU family, model, model name and stepping
- CPU cache size and MHz

The following items would need to be addressed:
- [ ] Decide if these should be resource level attributes or datapoint level attributes on the existing `system.cpu.*` metrics
- [ ] Scope what attributes we consider important
- [ ] Standardize the name of these attributes

This would be part of open-telemetry/opentelemetry-specification/issues/3556 if approved.

**Comment by ChrsMark** [comment]
Hey @mx-psi are you planning to work on this? If not, I can work on this!

**Comment by mx-psi** [comment]
I am going to focus on other issues for now so feel free to work on this @ChrsMark!

**Comment by ChrsMark** [comment]
Tasks:

- [ ] CPUINFO static info:  https://github.com/open-telemetry/semantic-conventions/pull/209
- [ ] Frequency will be added as metric as decided at https://github.com/open-telemetry/semantic-conventions/pull/209#issuecomment-1665176101: TBA


@mx-psi is there any related issue for adding these in `hostmetricsreceiver`? I would like to give it a shot :).

**Comment by mx-psi** [comment]
> is there any related issue for adding these in hostmetricsreceiver? I would like to give it a shot :).

No, but feel free to create one, I am happy to help there and review! I am not sure whether we want the resource attributes on `hostmetricsreceiver` or the [`resourcedetectionprocessor` system detector](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/processor/resourcedetectionprocessor#system-metadata). I would say probably system detector, since these attributes could be useful on any type of telemetry and not just on the cpu metrics, but we can discuss this on the Collector :)

**Comment by ChrsMark** [comment]
Before moving to the cpu's frequencies metrics we need to address https://github.com/open-telemetry/semantic-conventions/issues/325 first since for the frequency we will need to report the core's ID along with the frequency metric.
