### ISSUE TITLE
Discuss where to get the information for `os.build_id`

### ISSUE THREAD

**Issue by ysolomchenko** [open-telemetry/semantic-conventions#1318]
### Area(s)

area:os

### Is your change request related to a problem? Please describe.

It's confusing that different Linux distributions keep OS build ID information in different places. This inconsistency makes it hard to find and access this info.

### Describe the solution you'd like

Let's create a look up OS build ID info, similar to how the [Non-Privileged Machine ID Lookup](https://github.com/open-telemetry/semantic-conventions/blob/main/docs/resource/host.md#non-privileged-machine-id-lookup) is handled. This would make it easier to find and use the build ID info across all distributions and operating systems.

**Comment by trask** [comment]
related: #1329
