### ISSUE TITLE
Misleading Description of db.namespace in Documentation - References Server Address and Port

### ISSUE THREAD

**Issue by agent-adam** [open-telemetry/semantic-conventions#1321]
### Area(s)

area:db

## Description
The documentation for the db.namespace attribute mentions  "fully qualified within the server address and port." don't think the server address is or should be part of the database name.

### Semantic convention version

1.27

**Comment by lmolkova** [comment]
> The documentation for the db.namespace attribute mentions "fully qualified within the server address and port." don't think the server address is or should be part of the database name.

Thank you for reporting this! Could you please elaborate on what's misleading?

The intention is that `db.namespace` does not contain `server.address|port`, but uniquely identifies a database that's hosted there.

E.g. I can have mysql running  on `localhost:3306` and two databases `user` and `orders` there. 
When connecting to/querying from `users`, it would result in the following attributes:
- `server.address = localhost`
- `server.port = 3306`
- `db.namespace = user`

When querying from `orders`, it would result in
- `server.address = localhost`
- `server.port = 3306`
- `db.namespace = orders`

**Comment by agent-adam** [comment]
Might just be a miss reading from my end. I see it means that it's the fully qualified name of the database within the context of that server and does not include the server address and port values directly
