### ISSUE TITLE
Yaml schema: unify semconv identity property

### ISSUE THREAD

**Issue by lmolkova** [open-telemetry/semantic-conventions#1324]
- attributes have `id`
- events have `name`
- metrics have `metric_name`
- resource have `name`

resources and spans don't have identity except the group-id.

We should consider unifying a property that describes a full name of a thing, especially if it's meaningful outside of semconv repo, e.g. for code generation and instrumentations.

**Comment by jsuereth** [comment]
resources now have name, which denote a "TYPE" identity, awkwardly.
