### ISSUE TITLE
Concerns about high cardinality in GraphQL span names

### ISSUE THREAD

**Issue by kaylareopelle** [open-telemetry/semantic-conventions#1361]
### Area(s)

area:graphql

### Is your change request related to a problem? Please describe.

The Ruby SIG has some concerns about the cardinality of span names for the current GraphQL semantic convention.

@karmingc [opened a PR on the opentelemetry-ruby-contrib repo to update the GraphQL span names](https://github.com/open-telemetry/opentelemetry-ruby-contrib/pull/966). 

This would update Ruby's existing name, `graphql.execute_query`, to [the current semantic convention's format, `<graphql.operation.type> <graphql.operation.name>`.](https://github.com/open-telemetry/semantic-conventions/blob/main/docs/graphql/graphql-spans.md?plain=1#L12-L15)

During review, @robertlaurin raised a concern about unbounded cardinality for the span names if operation name and operation type are included:
> ...OpenTelemetry consistently discourages high cardinality span names, and this by definition is unbounded cardinality.
>
> GraphQL operation name is just a free form label supplied by the client caller. There's absolutely no constraints, if we don't put the raw path in an http server span name, I'm not at all convinced we should all operation name here.
>
> Fwiw query, mutation, subscription seems reasonable on its own.
[(source)](https://github.com/open-telemetry/opentelemetry-ruby-contrib/pull/966/files#r1597133695)

The PR is currently blocked until we can come to a resolution about the appropriate span name.  

### Describe the solution you'd like

`<graphql.operation.type>` seems sufficient, since the `<graphql.operation.name>` is available in span attributes. 

### Describe alternatives you've considered

The GraphQL semantic convention could also be updated to more closely match the DB span name, by adding a `SHOULD` instead of a `MUST` for the name and/or add the `low_cardinality` caveat about `db.operation.name`. 

> The span name SHOULD be {db.operation.name} {target} if there is a (low-cardinality) {db.operation.name} available (see below for the exact definition of the [{target}](https://opentelemetry.io/docs/specs/semconv/database/database-spans/#target-placeholder) placeholder).
[[source]](https://github.com/open-telemetry/semantic-conventions/blob/main/docs/database/database-spans.md?plain=1#L59-L60)

### Additional context

This may be similar to https://github.com/open-telemetry/semantic-conventions/issues/182, but since the problem focuses specifically on the span name, I thought it warranted a new issue.

**Comment by joaopgrassi** [comment]
@kaylareopelle since you folks have good ideas on how to move forward, are you opening a PR to change it?

**Comment by kaylareopelle** [comment]
Hi @joaopgrassi! I can open a PR to change it! This is my first time interacting with the semantic conventions repo, so I wasn't exactly sure about the process.

**Comment by joaopgrassi** [comment]
Perfect, thank you! I will assign this to you then. Feel free to reach out if you need help with anything.

**Comment by kaylareopelle** [comment]
Hi @joaopgrassi! I've opened a PR for this change: https://github.com/open-telemetry/semantic-conventions/pull/1389
