### ISSUE TITLE
Should `system` metrics be renamed to `os` (for consistency with attributes)?

### ISSUE THREAD

**Issue by lmolkova** [open-telemetry/semantic-conventions#1371]
We have `os.name`, `os.version`, type, etc attributes, but use `system` on metrics  (`system.cpu.time`, `system.memory.usage`, etc).

System metrics are effectively OS metrics: 

https://github.com/open-telemetry/semantic-conventions/blob/5eb37f706894718493af7a668971c651acb80812/docs/system/system-metrics.md?plain=1#L14-L15

We should consider renaming `system` to `os` (i.e. (`os.cpu.time`, ...) for the sake of consistency.

Also I'd expect system metrics to be reported with `os` resource (it's useful to know the OS type when interpreting specific metric), but it's not documented.

**Comment by heyams** [comment]
check here:  https://github.com/open-telemetry/semantic-conventions/blob/3146dc01dc4ab477549f51ceed3b8f8cb98b5829/specification/metrics/semantic_conventions/system-metrics.md#systemos---os-specific-system-metrics

**Comment by lmolkova** [comment]
> check here: https://github.com/open-telemetry/semantic-conventions/blob/3146dc01dc4ab477549f51ceed3b8f8cb98b5829/specification/metrics/semantic_conventions/system-metrics.md#systemos---os-specific-system-metrics

I assume it could still be `os.windows` or `os.linux` instead of `system.windows` and `os.linux`. Or do I miss something?

**Comment by ChrsMark** [comment]
> We have os.name, os.version, type, etc attributes, but use system on metrics (system.cpu.time, system.memory.usage, etc).

Similarly we have `host.*` namespace which is not merged to the `system.*`. We had agreed as a WG group that `host.*` will be used for resource attributes of a system while the `system.*` namespace will be used for the metrics.

I assume the same applies for the `os.*` resource attributes which are separate and describe a distinct set of information.

> We should consider renaming system to os (i.e. (os.cpu.time, ...) for the sake of consistency.

We would need some concrete use cases to change the current model which is widely used extensively by the Collector users.

**Comment by mx-psi** [comment]
We discussed this at KubeCon NA 2024 at 2024-11-14. We think we should keep things as is but document what each namespace is meant for.

**Comment by mx-psi** [comment]
Removing system blocker label (since it is already at the parent issue)

**Comment by lmolkova** [comment]
closing in favor of a better description to be added in #1578
