### ISSUE TITLE
Migrate CHANGELOG from specification over, keeping only SEMCONV sections.

### ISSUE THREAD

**Issue by jsuereth** [open-telemetry/semantic-conventions#14]

**Comment by reyang** [comment]
This is resolved by #18.

**Comment by arminru** [comment]
@reyang I think either is fine. It would be a one-time effort to copy them over and would provide a nicer experience (one can ctrl+f in this one single file) but adding a line saying the following should also be enough:

> Previously, the semantic conventions in this repository were part of [open-telemetry/opentelemetry-specification](https://github.com/open-telemetry/opentelemetry-specification), for which the changelog can be found [here](https://github.com/open-telemetry/opentelemetry-specification/blob/main/CHANGELOG.md).

**Comment by jsuereth** [comment]
Our automation for schema_url basically *requires* historical changes.  Effectively it uses version numbers in CHANGELOG.md to verify schema_url accounts for all of them.
