### ISSUE TITLE
areas-downdown-check template is out of date

### ISSUE THREAD

**Issue by heyams** [open-telemetry/semantic-conventions#1509]
### What happened?

`Dropdowns in issue templates is out of date, please run "make generate-gh-issue-templates" and commit the changes in this PR.`

![image](https://github.com/user-attachments/assets/d30f01b9-7827-466f-9468-ed35fb71211b)

### Semantic convention version

1.28.0

**Comment by heyams** [comment]
not sure is this expected? how long has it been like this?

**Comment by joaopgrassi** [comment]
I'm going to take a look.

**Comment by joaopgrassi** [comment]
@heyams where are you seeing this? If it is happening in a PR, you need to follow the message and run the make command. It happens when you introduce a new area, which then needs to be added there so the issue templates/labels contain the new area.

**Comment by joaopgrassi** [comment]
I see it happened in this PR https://github.com/open-telemetry/semantic-conventions/pull/1456 but you fixed it so closing as it works as expected.
