### ISSUE TITLE
Request: add @rogercoll in System Metrics approvers 

### ISSUE THREAD

**Issue by mx-psi** [open-telemetry/semantic-conventions#1540]
I would like to nominate @rogercoll as System Metrics approver (@open-telemetry/semconv-system-approvers).
Roger has been regularly attending the System Semantic Conventions WG meetings and participating in the discussions, and has also [authored](https://github.com/open-telemetry/semantic-conventions/pulls?q=+is%3Apr+author%3Arogercoll+) and [reviewed](https://github.com/open-telemetry/semantic-conventions/pulls?q=is%3Apr+reviewed-by%3Arogercoll+) PRs [and issues](https://github.com/open-telemetry/semantic-conventions/issues?q=+is%3Aissue+author%3Arogercoll+) related to system semantic conventions, 

cc: @braydonk @ChrsMark @dmitryax @jsuereth @open-telemetry/semconv-system-approvers @open-telemetry/specs-semconv-approvers @open-telemetry/specs-semconv-maintainers

**Comment by ChrsMark** [comment]
I support!

**Comment by braydonk** [comment]
I support as well!

**Comment by dmitryax** [comment]
I support!

**Comment by lmolkova** [comment]
Done https://github.com/orgs/open-telemetry/teams/semconv-system-approvers/members! 

Welcome @rogercoll! 🎉

**Comment by rogercoll** [comment]
Thanks! 🎉
