### ISSUE TITLE
Mark .NET runtime metrics as stable

### ISSUE THREAD

**Issue by lmolkova** [open-telemetry/semantic-conventions#1602]
.NET runtime metrics are part of stable (as of last week) .NET 9. 
https://github.com/dotnet/runtime/blob/v9.0.0/src/libraries/System.Diagnostics.DiagnosticSource/src/System/Diagnostics/Metrics/RuntimeMetrics.cs

We should mark them as stable.

_Originally posted by @lmolkova in https://github.com/open-telemetry/semantic-conventions/pull/1364#discussion_r1852771509_

**Comment by lmolkova** [comment]
@open-telemetry/semconv-dotnet-approver @stevejgordon would someone be able to work on it?

**Comment by stevejgordon** [comment]
@lmolkova, I can pick this up.
