### ISSUE TITLE
Add @maryliag to database semconv approvers

### ISSUE THREAD

**Issue by lmolkova** [open-telemetry/semantic-conventions#1605]
We really appreciate @maryliag's work on DB semantic conventions prototyping changes in JS, reviewing semconv PRs and participating in SIG meetings.  I'd like to nominate her to become official database approver.

/cc @open-telemetry/semconv-db-approvers

**Comment by trask** [comment]
I support

**Comment by lmolkova** [comment]
Yay! https://github.com/orgs/open-telemetry/teams/semconv-db-approvers/members
