### ISSUE TITLE
Chloggen should generate links for PRs

### ISSUE THREAD

**Issue by lmolkova** [open-telemetry/semantic-conventions#1627]
Changelog contains PR numbers which are not automatically recognized as links when they are committed to the repo.

https://github.com/open-telemetry/semantic-conventions/blob/07293edd52e2182f9c18e871bbff44958cf77271/CHANGELOG.md?plain=1#L15

It'd be great to make chloggen produce links for them.

**Comment by joaopgrassi** [comment]
Alright, I was unaware that GitHub automatically redirects correctly PRs/Issues, so we don't need changes in the tool. Just a custom template.
