### ISSUE TITLE
Add metrics for k8s statefulset

### ISSUE THREAD

**Issue by ChrsMark** [open-telemetry/semantic-conventions#1637]
### Area(s)

area:k8s

### Is your change request related to a problem? Please describe.

Part of https://github.com/open-telemetry/semantic-conventions/issues/1032.

This issue is for adding the `statefulset` related metrics.

### Describe the solution you'd like

The following metrics are already implemented by the Collector:
`k8s.statefulset.desired_pods`
`k8s.statefulset.ready_pods`
`k8s.statefulset.current_pods`
`k8s.statefulset.updated_pods`

ref: https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/v0.114.0/receiver/k8sclusterreceiver/documentation.md#k8sstatefulsetcurrent_pods

### Additional context

API ref: https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.30/#statefulsetstatus-v1-apps

I would like to validate the names here though and make sure that we are happy with the `.ready_pods` and `.desired_pods`. The alternative would be to have them as `.desired` and `.available` as we have in the `deployment` and `replicaset` metrics (https://github.com/open-telemetry/semantic-conventions/pull/1636)?

@TylerHelmuth @povilasv @dmitryax could you verify if that's the desired modeling here for any specific reason or if it would make sense to change it so as to be consistent with the other mentioned namespaces?

**Comment by dmitryax** [comment]
I think the existing naming is good. I don't think k8s.statefulset.pods namespace would make sense

**Comment by dmitryax** [comment]
I don't remember any history behind these names. It makes sense to keep it consistent with other metrics and drop _pods suffix

**Comment by tetianakravchenko** [comment]
> I would like to validate the names here though and make sure that we are happy with the .ready_pods and .desired_pods. The alternative would be to have them as .desired and .available as we have in the deployment and replicaset metrics (https://github.com/open-telemetry/semantic-conventions/pull/1636)?

`k8s.statefulset.desired_pods` fully match to the similar deployment/replicaset metrics, as it relies on the [spec.replicas](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/receiver/k8sclusterreceiver/internal/statefulset/statefulsets.go#L28). Using the similar naming I think is a good idea - `k8s.statefulset.desired`

`k8s.statefulset.ready_pods` - is actually relying on [`Status.ReadyReplicas`](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/receiver/k8sclusterreceiver/internal/statefulset/statefulsets.go#L31) not on the `Status.AvailableReplicas`. It wouldn't be correct to rename `k8s.statefulset.ready_pods` to `k8s.statefulset.available`

**Comment by ChrsMark** [comment]
> > I would like to validate the names here though and make sure that we are happy with the .ready_pods and .desired_pods. The alternative would be to have them as .desired and .available as we have in the deployment and replicaset metrics (#1636)?
> 
> `k8s.statefulset.desired_pods` fully match to the similar deployment/replicaset metrics, as it relies on the [spec.replicas](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/receiver/k8sclusterreceiver/internal/statefulset/statefulsets.go#L28). Using the similar naming I think is a good idea - `k8s.statefulset.desired`
> 
> `k8s.statefulset.ready_pods` - is actually relying on [`Status.ReadyReplicas`](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/receiver/k8sclusterreceiver/internal/statefulset/statefulsets.go#L31) not on the `Status.AvailableReplicas`. It wouldn't be correct to rename `k8s.statefulset.ready_pods` to `k8s.statefulset.available`

Good point! So if we are ok with removing the `_pods` suffix the suggest metrics' names would be the following:

```
k8s.statefulset.desired
k8s.statefulset.ready
k8s.statefulset.current
k8s.statefulset.updated
```

**Comment by TylerHelmuth** [comment]
There is also the pattern of `k8s.daemonset.current_scheduled_nodes` to consider. 

One issue I have with `k8s.statefulset.ready` is that it implies (to mean at least) to be a metric concerning the number of ready statefulsets, but that is not what it is counting.

**Comment by ChrsMark** [comment]
Same issue seems to appear for the deployment, replicaset etc resources: https://github.com/open-telemetry/semantic-conventions/pull/1636

`k8s.deployment.desired` might again be received (wrongly) as number of desired deployments, no?

**Comment by TylerHelmuth** [comment]
Bummer, we'll already inconsistent 😢

**Comment by dmitryax** [comment]
This is an interesting topic. Keep in mind that we also have `k8s.container.ready` which has a completely different meaning but sounds like `k8s.statefulset.ready`. It doesn't seem right. We also have `k8s.daemonset.ready_nodes`. Now I'm thinking it may be better to add the `_pods` suffix to other metrics in https://github.com/open-telemetry/semantic-conventions/pull/1636 if we want consistency. WDYT?

**Comment by jaronoff97** [comment]
should we attempt to align more closely with what KSM [has here](https://github.com/kubernetes/kube-state-metrics/blob/main/docs/metrics/workload/deployment-metrics.md)? i.e. `k8s.deployment.ready_replicas` or `k8s.deployment.status.replicas_ready`?

**Comment by ChrsMark** [comment]
+1 for having consistency here.

We can add the `_pods` or `_replicas` suffix as it was mentioned. This would also be in-line with the pluralization guideline: https://github.com/open-telemetry/semantic-conventions/blob/2d34907ac6d08735060f19c759771dd37ff36ee7/docs/general/metrics.md?plain=1#L131-L146 

I would be more in favor of `k8s.deployment.available_replicas`, `k8s.deployment.desired_replicas`, `k8s.statefulset.desired_replicas` etc.

We cannot really reduce the number of breaking changes. 4 statefulset metrics come with the  `_pods` suffix while the [`hpa` metrics](https://github.com/open-telemetry/semantic-conventions/issues/1644) come with the `_replicas` one. The K8s API describes those fields as replicas so it seems `_replicas` is more consistent: https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.30/#statefulsetstatus-v1-apps

 `_replicas` is indeed aligned with KSM as it was mentioned [above](https://github.com/open-telemetry/semantic-conventions/issues/1637#issuecomment-2515582508) but it's not that KSM provides the best naming for all. See for example the [daemonset-metrics](https://github.com/kubernetes/kube-state-metrics/blob/main/docs/metrics/workload/daemonset-metrics.md) where the metrics are called like `kube_daemonset_status_number_ready`. For jobs it make sense to have the `_pods` suffix (i.e. `k8s.job.active_pods`) and for daemonsets the pattern of `k8s.daemonset.current_scheduled_nodes`.

I will group all the "replicas-related" together as part of the https://github.com/open-telemetry/semantic-conventions/pull/1636 to illustrate the idea and we can continue the discussion.
