### ISSUE TITLE
[docs] Refer to OTel spec at `main`?

### ISSUE THREAD

**Issue by chalin** [open-telemetry/semantic-conventions#179]
The docs contain links like this: https://github.com/open-telemetry/opentelemetry-specification/blob/v1.21.0.

Can these be changed to refer to `main`, or at least the latest version of the OTel spec?

/cc @svrnm @cartermp @jsuereth @joaopgrassi

**Comment by jsuereth** [comment]
We want to tie to a specific version of the specification from our work.  We have a script to automatically update version, I'll run that tied to this bug.

**Comment by chalin** [comment]
> We want to tie to a specific version of the specification from our work.

Ok

> We have a script to automatically update version

Good.

---

@jsuereth - I need to clarify something though. You had the following point, originally from https://github.com/open-telemetry/opentelemetry.io/pull/2908, but now tracked via:

- https://github.com/open-telemetry/opentelemetry.io/issues/2721:
  > - [ ] Ensure semantic-conventions -> specification links are accurately internalized to the website

Let's suppose that the website is hosting version X of the OTel spec. When publishing semconv, how should we handle links into the OTel spec? Consider these cases:

1. Semconv page links to OTel spec version X
2. Semconv page links to OTel spec version Y, where Y != X
3. Semconv page links to OTel spec at `main`

In cases (1) and (3), it makes sense to link to the website-local page of the spec. What shall we do in the case of (2), keep the external link? (Ideally, we want to keep readers on the website, but it might not be possible in this last case.)
