### ISSUE TITLE
Rename db.client.connections.usage to db.client.connections.count?

### ISSUE THREAD

**Issue by trask** [open-telemetry/semantic-conventions#201]
This seems more consistent with:

* `system.processes.count`

(though also could be `db.client.connections` based on outcome of #50)

**Comment by trask** [comment]
Examples of `.count`:

* `process.runtime.jvm.threads.count`
* `system.processes.count`

Examples of `.usage`:

* `db.client.connections.usage`
* `system.filesystem.usage` (`Bytes`)
* `system.memory.usage` (`Bytes`)
* `system.paging.usage`  (`Bytes`)
* `process.runtime.jvm.memory.usage` (`Bytes`)
* `process.runtime.jvm.memory.usage_after_last_gc` (`Bytes`)
* `hw.gpu.memory.usage` (`Bytes`)
* `hw.logical_disk.usage` (`Bytes`)

Proposal: recommend `.usage` when units are `Bytes`, otherwise recommend `.count`

**Comment by lmolkova** [comment]
Related: #703

**Comment by gregkalapos** [comment]
I'd be happy to create a PR for this.
