### ISSUE TITLE
network: address (+domain) attributes have confusingly inconsistent meanings

### ISSUE THREAD

**Issue by Oberon00** [open-telemetry/semantic-conventions#206]
It seems that server/client.socket.address are equivalent to source/destination.address while there is no attribute with equivalent meaning of server/client.address for source/destination (most closely seems to be source/destination.domain, which also exists under server/client.socket, but which seems to be defined solely for DNS names (why?), while server/client.address is more generic)

The `*.address` attributes:

* client.socket.address: "Immediate client peer address - unix domain socket name, IPv4 or IPv6 address."
* server.socket.address: "Physical server IP address or Unix socket address. If set from the client, should simply use the socket's peer address, and not attempt to find any actual server IP (i.e., if set from client, this may represent some proxy server instead of the logical server)." _(much more elaborate than client -- why?)_
* client.address: "Client address - unix domain socket name, IPv4 or IPv6 address. [1]" "[1]: When observed from the server side, and when communicating through an intermediary, client.address SHOULD represent client address behind any intermediaries (e.g. proxies) if it's available."
* server.address: "Logical server hostname, matches server FQDN if available, and IP or socket address if FQDN is not known." _(why no note about proxies here?)_
* source.address: "Source address, for example IP address or Unix socket name."
* destination.address: "Peer address, for example IP address or UNIX socket name." _(why does it use the removed term "peer" here? That would mean something rather different, and would match our old remote/local concept)_

The closely related `*.domain` attributes:

* _client.socket.domain seems to be missing?_
* server.socket.domain: "The domain name of an immediate peer. [1]" "[1]: Typically observed from the client side, and represents a proxy or other intermediary domain name."
* source.domain: "The domain name of the source system. [1] [1]: This value may be a host name, a fully qualified domain name, or another host naming format."
* destination.domain: "The domain name of the destination system. [1] [1]: This value may be a host name, a fully qualified domain name, or another host naming format."

This seems all rather messy to me, there is barely any any attribute pair with the symmetry I would have expected.

CC @lmolkova @jsuereth 

I feel like this should be addressed before stabilization (though the HTTP-specific meaning is hopefully clear enough given the additional context there so I wouldn't say it's a blocker for stabilizing HTTP -- might want to add a note that details regarding proxy address semantics might change though)

**Comment by lmolkova** [comment]
@Oberon00 could you please propose specific changes you'd like to see?

**Comment by Oberon00** [comment]
I mentioned some specific points I think are odd, and overall there is a lack of symmetry.

One concrete suggestion I can add: Move the current source/destination.address to source/destination.socket.address. Add a new source/destination.address that is equivalent to client/server.address.

Of course before that, client.address should be made symmetrical to server.address. (For example add to server.address: "When observed from the client side, and when communicating through an intermediary, server.address SHOULD represent client address behind any intermediaries (e.g. proxies) if it's available.", or remove the equivalent from client.addrress)

**Comment by trask** [comment]
> Of course before that, client.address should be made symmetrical to server.address. (For example add to server.address: "When observed from the client side, and when communicating through an intermediary, server.address SHOULD represent server address behind any intermediaries (e.g. proxies) if it's available.", or remove the equivalent from client.addrress)

this is done now (#244)

**Comment by trask** [comment]
> One concrete suggestion I can add: Move the current source/destination.address to source/destination.socket.address. Add a new source/destination.address that is equivalent to client/server.address.

I created #254 for this

**Comment by trask** [comment]
> The `*.address` attributes:
> 
> * client.socket.address: "Immediate client peer address - unix domain socket name, IPv4 or IPv6 address."
> * server.socket.address: "Physical server IP address or Unix socket address. If set from the client, should simply use the socket's peer address, and not attempt to find any actual server IP (i.e., if set from client, this may represent some proxy server instead of the logical server)." _(much more elaborate than client -- why?)_
> * client.address: "Client address - unix domain socket name, IPv4 or IPv6 address. [1]" "[1]: When observed from the server side, and when communicating through an intermediary, client.address SHOULD represent client address behind any intermediaries (e.g. proxies) if it's available."
> * server.address: "Logical server hostname, matches server FQDN if available, and IP or socket address if FQDN is not known." _(why no note about proxies here?)_
> * source.address: "Source address, for example IP address or Unix socket name."
> * destination.address: "Peer address, for example IP address or UNIX socket name." _(why does it use the removed term "peer" here? That would mean something rather different, and would match our old remote/local concept)_

I think all of these are addressed now

**Comment by trask** [comment]
> client.socket.domain seems to be missing?

I've opened #255 for this

**Comment by trask** [comment]
@Oberon00 can you check that I've accurately captured your remaining concerns about client/server/source/destination in these issues (and we can close this issue)?

* #250
* #251
* #254
* #255

**Comment by trask** [comment]
@Oberon00 it would be really helpful if you could take another pass and confirm that your concerns are covered by the 4 issues above, thx!

**Comment by Oberon00** [comment]
Hi, I will take a look by tomorrow at the same time

**Comment by Oberon00** [comment]
Just writing down my notes reading through again:

* Reverse DNS lookup should be centrally adressed in the markdown at one place. I think it is actually not that surprising that we don't want this to happen, so can we just generally say that for all the address and domain attributes, instrumentations SHOULD NOT do a DNS lookup on their own (neither forward nor reverse) but capture the result of the application/libraries lookup or not set the corresponding attribute at all (or in some cases set it to whichever of the set {IP, name} is available). This is not only due to performance but also to avoid reporting inaccurate information for multi-IP hosts by default.
