### ISSUE TITLE
http.server.active_requests usually does not have route attribute

### ISSUE THREAD

**Issue by lmolkova** [open-telemetry/semantic-conventions#221]
Routing usually happens after the request starts, so it's not possible up record +1 on `http.server.active_requests` and provide route.

Is there any instrumentation that can provide route data there? Should we consider removing the attribute?

**Comment by trask** [comment]
I don't see `http.route` listed as an attribute here: https://github.com/open-telemetry/semantic-conventions/blob/main/docs/http/http-metrics.md#metric-httpserveractive_requests

**Comment by lmolkova** [comment]
Indeed 😄 thank you!
