### ISSUE TITLE
Document the difference between a host and a system metric

### ISSUE THREAD

**Issue by frzifus** [open-telemetry/semantic-conventions#226]
This issue is intended to discuss the difference between the host and system namespace. The outcome should be a clear description of when which ns is used.

This question was raised during the [Aug 2, 2023, 08:30 PT SIG MTG](https://docs.google.com/document/d/1p5TH57t43XpxA48onLzX4PIr3g6ydYKCtR_AUlsCnQk/edit#heading=h.ldhv1fb8w5d) and needs to be answered to continue on this [PR](https://github.com/open-telemetry/semantic-conventions/pull/209#discussion_r1279445608).

**Comment by mx-psi** [comment]
cc @ChrsMark

**Comment by trask** [comment]
just in case it helps, there was a somewhat related prior discussion here: https://github.com/open-telemetry/opentelemetry-specification/pull/2388

**Comment by ChrsMark** [comment]
We had a discussion about this during the August 30th System Semantic Convention WG meeting. The main points were the following:

1) Keep using `host.*` namespace for resource attributes like `host.id`, `host.name` etc. This means that the [PR](https://github.com/open-telemetry/semantic-conventions/pull/209) which only adds "static" host's resource attributes is good to go from this perspective.
2) For metrics we can keep using the `system.*` namespace whenever we collect metrics from the system directly.
3) For centralized metrics that are collected from outside of the resource's scope (ie container metrics collected centrally for a k8s cluster) we can use resource specific namespace like for example `container.*`, `pod.*`, `vm.*`, `instance.*` etc. Containers, VMs etc are actually processes for a bare metal host similarly to what a `jvm` process is. This is also explained at https://github.com/open-telemetry/semantic-conventions/pull/87#discussion_r1282885340 and aligns with https://github.com/open-telemetry/opentelemetry-specification/pull/2388#issuecomment-1057120767.

@mx-psi @dmitryax @kaiyan-sheng feel free to correct me if I miss anything here. If we agree on this we can maybe transfer this conclusion somewhere for future reference (and then close this issue).

cc: @trask

**Comment by mx-psi** [comment]
Thanks for the summary @ChrsMark! I think there is agreement within the System semantic conventions WG. Given there has not been any disagreement voiced on this issue, I think we can open a PR to put this in writing somewhere: for (1) and (2) maybe on the README.md of the relevant folders on this repository, while I am not sure as to where to put (3)

**Comment by ChrsMark** [comment]
Thanks @mx-psi ! I can try to consolidate (1) and (2) in https://github.com/open-telemetry/semantic-conventions/blob/main/docs/resource/host.md and then (2) and (3) (rephrased) in https://github.com/open-telemetry/semantic-conventions/blob/main/docs/system/system-metrics.md.

For (2) and (3) we want something similar to https://github.com/open-telemetry/opentelemetry-specification/pull/2388/files#diff-48ed2e166c485f6f64a1a78251b07248e74e9c2a41cfe24e2950b07a5db196b2R10-R13 which was closed. Actually what we propose here is exactly the opposite with the content of that PR but aligns with https://github.com/open-telemetry/opentelemetry-specification/pull/2388#issuecomment-1057120767.

@trask if you have any suggestions or thoughts on this please let us know :).

**Comment by ChrsMark** [comment]
@frzifus @mx-psi since was merged I guess we can close this one?
