### ISSUE TITLE
Rename `process.runtime.jvm.*` namespace to simply `jvm.*`

### ISSUE THREAD

**Issue by trask** [open-telemetry/semantic-conventions#227]
From @jsuereth https://github.com/open-telemetry/semantic-conventions/pull/20#pullrequestreview-1549803871:

> We want namespacing to be "reasonably unique" and minimal.

This will help with keeping the attribute names under control as well, now that we are namespacing them also.

**Comment by trask** [comment]
comment from @tigrannajaryan https://github.com/open-telemetry/semantic-conventions/pull/20#discussion_r1252216178

> What is our general strategy with regards to choosing top-level namespaces? Is every language free to put anything in the top-level namespace (like Java does with 'jvm.`)? My concern is that this is going to result in highly crowded top-level that is going to be hard to manage. How do we make sure languages don't step on each other's toes? A language can choose to use a namespace and later it turns out to be also needed for another language but can mean something different.
>
> I would like to understand what the policy is in general and I don't see it mentioned anywhere.

**Comment by trask** [comment]
> I would like to understand what the policy is in general

my guess(?) is that it is up to the discretion of @open-telemetry/specs-semconv-maintainers to approve any new top-level namespaces.

@tigrannajaryan are you looking for something more than this?

**Comment by jsuereth** [comment]
@tigrannajaryan may still be out on Holiday.  His request, in the TC, was that we set a consistent definition of what makes a namespace and what doens't.

E.g. we should haven't a metric namespace `runtime.process.jvm` and an attribute namespace `jvm`.  We should consistently have namespace rules so that like things have like namespaces.  

THis is where the "reasonably unique" language came from, we just need to codify it in a PR.

**Comment by liustanley** [comment]
Are there any future plans of making the runtime metric prefix consistent across the different language instrumentations? All of the other language instrumentation libraries use `process.runtime.[language]`.

**Comment by trask** [comment]
hi @liustanley, I think this is a good question, can you open a new issue for it?
