### ISSUE TITLE
Question about `OTEL_SEMCONV_STABILITY_OPT_IN`

### ISSUE THREAD

**Issue by TimothyMothra** [open-telemetry/semantic-conventions#240]
I'm working on [Semantic Conventions for Http](https://github.com/open-telemetry/semantic-conventions/blob/main/docs/http/README.md) which defines the Environment Variable `OTEL_SEMCONV_STABILITY_OPT_IN` as a list of comma-separated values.

How should I handle if multiple values have been set?

For example:
```
$env:OTEL_SEMCONV_STABILITY_OPT_IN = "http,http/dup"
```

What's the expected behavior?
1. Honor first value
2. Honor last value
3. Treat this as invalid and use default behavior.

**Comment by joaopgrassi** [comment]
I would see it as an invalid value, log an warning maybe and fallback to the default behavior. We should probably document this if we decide to go this route.

**Comment by pellared** [comment]
Maybe we could change the values to something like `http/stable` and `http/legacy`? The user would provide `http/legacy,http/stable` instead of `http/dup`.

**Comment by mateuszrzeszutek** [comment]
[This is how we implemented that in the Java instrumentation](https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/main/instrumentation-api/src/main/java/io/opentelemetry/instrumentation/api/internal/SemconvStability.java) -- I chose to just sum up the boolean values and enable everything. Even if this is technically invalid value, I think this is probably a bit gentler to the user who just wanted both options and typed all the settings.

**Comment by TimothyMothra** [comment]
I don't have a strong preference, but I think @mateuszrzeszutek approach is the most user friendly.

I fully agree with @joaopgrassi that this should be added to the documentation.
Are there any other csv configurations in OTel that could be used as precedent here?
