### ISSUE TITLE
Request to add more semconv-jvm-approvers

### ISSUE THREAD

**Issue by trask** [open-telemetry/semantic-conventions#242]
I'd like to request adding @mateuszrzeszutek @jack-berg @jonatan-ivanov to the @open-telemetry/semconv-jvm-approvers group, thx!

**Comment by reyang** [comment]
We should be all set here:

![image](https://github.com/open-telemetry/semantic-conventions/assets/17327289/a2647815-8251-4460-bcd1-1c1aa456cf7f)
