### ISSUE TITLE
Disconnect between server/client(.socket).port and network.transport (TCP/UDP)

### ISSUE THREAD

**Issue by trask** [open-telemetry/semantic-conventions#250]
> It seems that the `network.transport` attribute was moved to trace-specific attributes, and the port is ambiguous if we don't know whether it was UDP or TCP

_Originally posted by @Oberon00 in https://github.com/open-telemetry/semantic-conventions/pull/244#discussion_r1289803009_

**Comment by trask** [comment]
> It seems that the `network.transport` attribute was moved to trace-specific attributes

I sent #256 for this

> and the port is ambiguous if we don't know whether it was UDP or TCP

@Oberon00 can you clarify if you think there's a specific change you're thinking that we should make related to this? thx

**Comment by trask** [comment]
@Oberon00 i'm not clear about this part

> and the port is ambiguous if we don't know whether it was UDP or TCP

and want to make sure we're not missing something that's needed for HTTP stability, thx!

**Comment by Oberon00** [comment]
The issue I mentioned on the ticket is resolved with #256. I can make another suggestion on the port specification.
