### ISSUE TITLE
Add `client.socket.domain` for symmetry with `server.socket.domain`

### ISSUE THREAD

**Issue by trask** [open-telemetry/semantic-conventions#255]
Originally from https://github.com/open-telemetry/semantic-conventions/issues/206#issue-1819655650

**Comment by trask** [comment]
One idea @lmolkova and I briefly discussed (not sure if it's a good idea or not yet) is that since `server.socket.domain` is very specific to proxy use case, maybe it could be renamed to `proxy.address`?

**Comment by Oberon00** [comment]
It could be a proxy or reverse proxy. How about peer.address? (Only half joking)

**Comment by trask** [comment]
`server.socket.domain` has been removed now (it was not carried over to the new `network.peer/local.*`)

the thought is to revisit the use case for `server.socket.domain` (forward proxies) in the future, potentially with new attribute(s), e.g. `proxy.address`

so I think this can probably be closed
