### ISSUE TITLE
Add system.linux.memory.available metric

### ISSUE THREAD

**Issue by ItsLastDay** [open-telemetry/semantic-conventions#257]
**What are you trying to achieve?**

Linux kernel exposes a memory metric called `available`, which helps to understand how much memory is really available for the userspace apps. See https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/7417.

This value is unique to Linux, hence the `system.linux` prefix: see https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/19149#issuecomment-1467634451.

**What did you expect to see?**

`system.linux.memory.available` - Gauge metric of integer type, meaning number of bytes available. No attributes.

**Additional context.**

https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/7417#issuecomment-1668082340

cc @dmitryax @braydonk

**Comment by ItsLastDay** [comment]
Great! I'll prepare a PR in a week or two, after Braydon merges his https://github.com/open-telemetry/semantic-conventions/pull/160.

**Comment by mx-psi** [comment]
Sorry for the spammy messages. I think this is unblocked now after #89? Or would we expect this to be under process metrics?

**Comment by braydonk** [comment]
Actually I think it is unblocked. I'm not sure why I suggested we wait until my PR is merged, I think I was mistaken. @ItsLastDay I believe you can move forward with this by adding it to the appropriate spot in the new yaml in #89.

**Comment by ItsLastDay** [comment]
Ack, will do.

**Comment by ItsLastDay** [comment]
https://github.com/open-telemetry/semantic-conventions/pull/323
