### ISSUE TITLE
HTTP span name for unknown methods

### ISSUE THREAD

**Issue by lmolkova** [open-telemetry/semantic-conventions#268]
HTTP spec currently requires to use `http.request.method`:

https://github.com/open-telemetry/semantic-conventions/blob/098db1ca510da01fe941f6c6308aad5000def910/docs/http/http-spans.md?plain=1#L69-L70

For custom/unsupported methods, it means `_OTHER`, however user experience could arguably be better if span names represented the original method such as `get` or `ACL`, which are captured in ``http.request.method_original``.

The argument for `_OTHER` is low cardinality, but it is not a clear requirement - https://github.com/open-telemetry/opentelemetry-specification/issues/3534.

Span name is a [part of stability guarantees](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/versioning-and-stability.md?plain=1#L188)

**Comment by trask** [comment]
> The span name SHOULD be the most general string that identifies a (statistically) interesting *class of Spans*

If the unknown methods are valid, then each unknown method makes an interesting group of span names

but if the unknown methods are invalid (spam), then grouping them all together makes an interesting group of span names

**Comment by lmolkova** [comment]
users and backends can still group using an attribute.

I just imagine spans looking like `_OTHER` in the list of span names - the immediate thing I'd do is to open the span to find out what it actually is, but if I see `ThIS is SPaM`, I immediately know what it is. And from my perspective, span names goal is to provide a quick summary of what it is

**Comment by Oberon00** [comment]
The span names primary purpose is grouping Low cardinality is more important than human-readability, that is what the spec says. A cardinality explosion in thr soan name is just as bad as in a metric dimension.

Backends can (and probably should) generate a different display name based on attributes.

**Comment by Oberon00** [comment]
I think it could still make sense to define a speial case for "_OTHER" like "HTTP _OTHER", but OTOH, the spans were previously named "HTTP <method>", which was removed in #3165 (personally, I thought the variant with "HTTP <method>" was better)

**Comment by trask** [comment]
I kind of like the span name `HTTP` for the case where we don't have a known http method

**Comment by joaopgrassi** [comment]
> A nice this about this naming is that those spans will be more identifiable in a U/X as HTTP, as opposed to only saying `_OTHER`

But that is something a back-end can easily do as a UI-only tweak. For ex Jaeger does this already - The URL is shown together with the name. I think other back-ends also do something similar OR can do if they want.

**Comment by Oberon00** [comment]
> But that is something a back-end can easily do as a UI-only tweak.

No. It would need to determine that the span name comes from HTTP conventions. These can be mixed with other conventions and often HTTP is not the primary one. So this is not easy even though it may be doable, at least heuristically.

> All to say I'm unsure if changing the spec to convey such UI feature makes sense.

This is not (only) an UI feature. It also avoid potential name collisions where unrelated spans would then group together (when using span name). Especially _OTHER was IIRC agreed upon as a standard enum value, so it may turn up in other conventions as well as span name.

**Comment by lmolkova** [comment]
updated #270 to use HTTP, PTAL
