### ISSUE TITLE
Move existing Kafka metrics to a JMX specific namespace

### ISSUE THREAD

**Issue by pyohannes** [open-telemetry/semantic-conventions#269]
### Problem

The [Kafka metrics in the messaging semantic conventions](https://github.com/open-telemetry/semantic-conventions/blob/main/docs/messaging/kafka.md#general-metrics) are based on metrics as they are reported by the JMX reporter. Although the JMX reporter is the [default reporter](https://docs.confluent.io/platform/current/kafka/monitoring.html), different reporters can be configured.

In their current form, the definition of those metrics causes confusion, as they suggest being an authoritative definition of metrics as they are reported by Kafka. However, they look different from the [metrics in the official Kafka documentation](https://kafka.apache.org/documentation/#monitoring), and they are different from the [OTLP metrics defined in KIP-714](https://cwiki.apache.org/confluence/display/KAFKA/KIP-714%3A+Client+metrics+and+observability#KIP714:Clientmetricsandobservability-Standardproducermetrics).

Based on feedback from @AndrewJSchofield, people involved in the Kafka project currently don't have an interest in defining and maintaining a definition of Kafka metrics as part of the OTel semantic conventions.

### Desired solution

The semantic conventions should make it clear that the existing metrics are JMX specific, ideally in the metric name. This allows support for conventions for Kafka metrics that are sent via a different reporter.

Even more importantly, this avoids confusion, as _it makes clear that the OTel semantic conventions are not the place that provides an authoritative definition of Kafka metrics_.

**Comment by pyohannes** [comment]
> The lack of mapping to semantic conventions doesn't mean this data is not useful.

I fully agree, [.NET runtime metrics](https://github.com/open-telemetry/opentelemetry-dotnet-contrib/tree/main/src/OpenTelemetry.Instrumentation.Runtime#metrics) are a great example of this.

The conception that telemetry data needs to be covered by OTel semantic conventions in order to be useful leads to unwanted side effects:
1. Semantic conventions are written to comply with existing instrumentation, whereas it should be the other way round.
2. As a consequence of the point above, we end up with a bunch of experimental semantic conventions with no clearly defined ownership.

My take is that telemetry conventions referring to a specific component (e. g. Kafka broker, or .NET runtime) _can_ be part of OTel semantic conventions, but can as well live apart of them. In any case, they should be maintained by people working on that specific component, and not by the wider community.

**Comment by joaopgrassi** [comment]
> My take is that telemetry conventions referring to a specific component (e. g. Kafka broker, or .NET runtime) _can_ be part of OTel semantic conventions, but can as well live apart of them. In any case, they should be maintained by people working on that specific component, and not by the wider community.

I agree as well. For me, what is a bit unclear is: If I specify such conventions outside OTel, should they follow the OTel guidelines? For ex, metrics names, instrument types and etc? 

To me it makes sense that if such library/framework etc uses OTel components to record such data (tracer, meter) they must follow the OTel guidelines.

**Comment by pyohannes** [comment]
Discussed in the semantic conventions SIG meeting on September 18th.

There was an agreement to remove experimental Kafka metrics from the semantic conventions. If a definition or reference of those metric is needed, it should be provided by the documentation of the package that synthesizes those metrics. It seems this [documentation is already available in the `kafkametricsreceiver` collector component](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/receiver/kafkametricsreceiver/documentation.md).
