### ISSUE TITLE
Add markdown document for `error` semconv

### ISSUE THREAD

**Issue by lmolkova** [open-telemetry/semantic-conventions#279]
https://github.com/open-telemetry/semantic-conventions/pull/205#discussion_r1296759270

#205 introduces `error.id` attribute, but it can be used by other instrumentations and deserves its own md file (or place in attribute registry)

**Comment by joaopgrassi** [comment]
The `error` namespace was moved to the attributes registry in https://github.com/open-telemetry/semantic-conventions/pull/500. Closing this.
