### ISSUE TITLE
Add jvm memory metric from MemoryMXBean

### ISSUE THREAD

**Issue by aheling11** [open-telemetry/semantic-conventions#286]
I am currently implementing the Skywalking metrics receiver in the OpenTelemetry Collector [(related issue)](https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/20315) 

Skywalking Java agent collects JVM data and I noticed that it collects both memory and memoryPool metrics. However, I found that in the OpenTelemetry JVM standard, only memoryPool metrics are defined (even though the metric name is jvm.memory.* , it is actually obtained from MemoryPoolMXBean#getUsage()). I am wondering if it is possible to also include memory metrics (obtained from MemoryMXBean) in the standard. 

My idea is to name the memory metrics as jvm.memory.* , and the memoryPool metrics as jvm.memoryPool.* or something else.

**Comment by trask** [comment]
hi @aheling11! Does the metrics backend you're using allow you to view total of the `jvm.memory.usage` metric, summed across its dimensions? I think that would give you the total memory usage and allow you to then drill into the dimensions as desired.

**Comment by aheling11** [comment]
> hi @aheling11! Does the metrics backend you're using allow you to view total of the `jvm.memory.usage` metric, summed across its dimensions? I think that would give you the total memory usage and allow you to then drill into the dimensions as desired.
I understand what you mean. I noticed that the jvm.memory.usage metric has a dimension called is_heap. I wrote a simple demo to test it by fetching the usage values from MemoryPoolMXBean and summing them up based on is_heap. The result is equal to usage values obtained from MemoryMXBean, both for heap and non-heap memory. It seems that the current semantic conventions meet my requirements. Thank you!

**Comment by aheling11** [comment]
I understand what you mean. I noticed that the jvm.memory.usage metric has a dimension called is_heap. I wrote a simple demo to test it by fetching the usage values from MemoryPoolMXBean and summing them up based on is_heap. The result is equal to usage values obtained from MemoryMXBean, both for heap and non-heap memory. It seems that the current semantic conventions meet my requirements. Thank you!

**Comment by aheling11** [comment]
Another question, The jvm.thread.count metric. I noticed that there is only one attribute called thread.daemon, but thread count can be divided into types such as blocked, waiting, runnable, etc.(skywalking agent collect all this metrics) Is it possible to add an attribute like thread.type to distinguish these metrics?

**Comment by mateuszrzeszutek** [comment]
> Another question, The `jvm.thread.count` metric. I noticed that there is only one attribute called `thread.daemon`, but thread count can be divided into types such as blocked, waiting, runnable, etc.(skywalking agent collect all this metrics) Is it possible to add an attribute like `thread.type` to distinguish these metrics?

There already is an issue about adding thread state: #101

**Comment by trask** [comment]
@aheling11 it would be great if you could add your use case for needing this additional dimension to #101, thx

**Comment by trask** [comment]
@aheling11 I'm going to close this and let's continue discussing in #101
