### ISSUE TITLE
Request to create semconv-system-approver

### ISSUE THREAD

**Issue by AlexanderWert** [open-telemetry/semantic-conventions#294]
I'd like to request creating a new approver group `semconv-system-approver` and add the following approvers to that group:

- @ChrsMark 
- @dmitryax 
- @frzifus 
- @kaiyan-sheng
- @mx-psi 

This group would be the code-owner for system-related semantic conventions including system-related resource (host, container, k8s, etc.) attributes as well as system metrics.

**Comment by mx-psi** [comment]
@arminru What should be the next steps for this?

**Comment by arminru** [comment]
I created https://github.com/orgs/open-telemetry/teams/semconv-system-approvers and added the initial members.

@kaiyan-sheng please follow the steps described here to join the OTel Github org so I can add you as well:
https://github.com/open-telemetry/community/blob/main/community-membership.md#member

@mx-psi The next steps would be to adapt the CODEOWNERS file in this repo here to add the new @open-telemetry/semconv-system-approvers group to the respective sub-folders/files.

**Comment by mx-psi** [comment]
Thanks! See #309 :)
