### ISSUE TITLE
Should we move common attribute documents from the spec repo to this repo?

### ISSUE THREAD

**Issue by joaopgrassi** [open-telemetry/semantic-conventions#295]
There's two documents in the spec repo that are relevant to semantic conventions:

- [Attribute naming](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/common/attribute-naming.md)
- [Attribute requirement level](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/common/attribute-requirement-level.md)

Should we consider moving those to the semantic conventions repo? I personally think they make more sense here, particularly the requirement level one.

I can work on moving them here, I just want to see what the community thinks

**Comment by mx-psi** [comment]
The 'Attribute requirement' doc  is specific to semantic conventions and IMO it should definitely be on this repository, but the 'Attribute naming; doc feels like a more general document that also applies to e.g. the design of Collector/SDK processors that add attributes or the development of internal-facing conventions, and thus I would leave that one on the specification repository.
