### ISSUE TITLE
Align networking conventions with ECS' `server.ip` and `client.ip`

### ISSUE THREAD

**Issue by trask** [open-telemetry/semantic-conventions#320]
I don't think we are currently set up well for pulling in ECS `server.ip` and `client.ip`.

Currently these fields would overlap heavily with our `server.socket.address` and `client.socket.address`.

If we do one more (last minute) remodeling, I think we can achieve alignment with ECS `server.ip`/`client.ip` AND bring clarity to the most confusing part of our networking conventions (`server.address` vs `server.socket.address` and `client.address` vs `client.socket.address`, a confusion that was mentioned in @Oberon00's #206, and which I have struggled with myself).

#### modeling the non-proxy case

* `server.socket.address` -> `server.ip`
* `client.socket.address` -> `client.ip`

`server.socket.address` and `client.socket.address` can be unix domain socket names, but unix domain socket names should go into `server.address` and `client.address` in the non-proxy case anyways

#### modeling the proxy case

* `server.socket.domain` -> `proxy.address`
* `server.socket.address` -> `proxy.address`/`proxy.ip`
* `server.socket.port` -> `proxy.port`
* `client.socket.address` -> `proxy.address`/`proxy.ip`
* `client.socket.port` -> `proxy.port`

cc @lmolkova @Oberon00 @AlexanderWert

**Comment by Oberon00** [comment]
I think this would be a quite important problem to address (or settle on never addressing)

**Comment by trask** [comment]
Closing, see https://github.com/open-telemetry/semantic-conventions/pull/342#issuecomment-1736634088:

> I'm thinking that maybe it's not worth trying to incorporate `client.ip` and `server.ip` into the HTTP semconv general modeling.
>
> I think `server.ip` (when captured) should be a resolved IP address for `server.address`, which means we wouldn't want to use `server.ip` like in https://github.com/open-telemetry/semantic-conventions/pull/321#issuecomment-1720609696:
>
> ![image](https://github.com/open-telemetry/semantic-conventions/assets/218610/1a4c2f6d-8eb1-4948-a64e-e4df608dbcf7)
>
> or on the client side to capture `server.ip` from the network connection, which could point to a forward proxy and not be a resolved IP address for `server.address`.
>
> I think `client.ip` and `server.ip` can still be brought into OpenTelemetry, but maybe they will have less significance in OpenTelemetry if we go forward with `network.peer.address` and `network.local.address` as proposed in this PR.
