### ISSUE TITLE
Revisit system cpu attributes

### ISSUE THREAD

**Issue by ChrsMark** [open-telemetry/semantic-conventions#325]
After https://github.com/open-telemetry/semantic-conventions/pull/89# is merged we need to revisit the `system.cpu.*` attributes and specifically the the `system.cpu.logical_number` as described at https://github.com/open-telemetry/semantic-conventions/pull/89#issuecomment-1715553729.

The idea here is that we should be consistent with the namespace that we use for the resource attributes. To my mind it should be `host.cpu.logical_number` similarly to to the `host.id` etc.

Related to https://github.com/open-telemetry/semantic-conventions/issues/308.

The goal of this is to ensure that we preserve a unified way for reporting metrics and resource attributes as part of the `system` and `host` namespaces. 

This is what https://github.com/open-telemetry/semantic-conventions/issues/226#issuecomment-1700529192 and https://github.com/open-telemetry/semantic-conventions/pull/324 try to address.

Also related to https://github.com/open-telemetry/semantic-conventions/issues/130 and its implementation PRs.

cc: @open-telemetry/semconv-system-approvers

**Comment by mx-psi** [comment]
> The idea here is that we should be consistent with the namespace that we use for the resource attributes. To my mind it should be host.cpu.logical_number similarly to to the host.id etc.

Just a small clarification: AIUI `system.cpu.logical_number` is not a resource attribute, but a metric attribute. I am in favor of being consistent between metric/span/log attributes namespacing and resource attribute namespacing but we need to be clear about this rule then!

**Comment by ChrsMark** [comment]
I see @mx-psi! So based on this the `system.cpu.logical_number` is fine as it is now? 

My concern was mostly about unifying the way we represent the attributes whenever is possible.

For example in that case we have the `system.cpu.logical_number` attribute for the metrics, but what if we would like to split host's metadata in the future per cpu's core_id? Would we introduce another one like `host.cpu.logical_number`?

So to my mind we could just use `host.cpu.logical_number` in both cases since the metric's attribute can be reflected as the resource's attribute as well.

**Comment by mx-psi** [comment]
Sorry for not replying on the issue, are there any questions remaining here? From the SIG I think what we discussed was that we will use the `host` namespace on the resource attribute and the `system` one for metrics. Is that a fair summary?

**Comment by ChrsMark** [comment]
>  From the SIG I think what we discussed was that we will use the host namespace on the resource attribute and the system one for metrics. Is that a fair summary?

I think it would bring less confusion to keep it like this!

Feel free to close it @mx-psi :)
