### ISSUE TITLE
Request to create semconv-mobile-approvers

### ISSUE THREAD

**Issue by AlexanderWert** [open-telemetry/semantic-conventions#343]
I'd like to request creating a new approvers group `semconv-mobile-approvers` that would be responsible for reviewing and maintaining semantic conventions related to the mobile domain (e.g. iOS, Android).

Folks proposed for that group / interested:

- @breedx-splk 
- @bryce-b 
- @LikeTheSalad 
- @nachoBonafonte 
- @bidetofevil
- @surbhiia
- @marandaneto

Related PRs and issues:

- https://github.com/open-telemetry/semantic-conventions/pull/67
- https://github.com/open-telemetry/semantic-conventions/pull/215
- https://github.com/open-telemetry/semantic-conventions/pull/293

**Comment by breedx-splk** [comment]
Count me in. Thanks!

**Comment by surbhiia** [comment]
If you need more approvers from Android, I would like to participate as well. :)

**Comment by marandaneto** [comment]
Same, I'd like to contribute as an approver if possible.

**Comment by bryce-b** [comment]
I'm in

**Comment by arminru** [comment]
I created @open-telemetry/semconv-mobile-approvers and added everyone stated in the description who is already a member of the OTel organization.

You can go ahead and update the code owners file to cover the subpaths where the mobile semantic conventions will reside.

@bidetofevil @surbhiia @marandaneto please take a look at our community membership guidelines and follow the process documented there for becoming a member so I can add you as well.

**Comment by marandaneto** [comment]
@arminru do you mean [this](https://github.com/open-telemetry/community/blob/main/community-membership.md#requirements)?

**Comment by arminru** [comment]
@marandaneto Exactly! Thanks for the link, I forgot to paste it above 🙂

**Comment by marandaneto** [comment]
> @marandaneto Exactly! Thanks for the link, I forgot to paste it above 🙂

Done, the issue is [open](https://github.com/open-telemetry/community/issues/1710), but I don't have sponsors nor have previously contributed directly.
How do I proceed? do I need to reach out to folks and try to get sponsors on my own? Also, do I need to contribute before being part of the new group?

**Comment by arminru** [comment]
Hey @marandaneto!

Only to become a formal approver you'd first need to be a community member, for which the requirements are defined in the community repo.

You're more than happy to already contribute to all efforts, working groups and discussions also as someone new to OpenTelemetry, and you're also able to review PRs. The only difference is that only approvals from formal approvers count towards our merge requirements.

The requirement for having sponsors for membership requests is to ensure those sponsors are able to confirm someone is a credible contributor with good reasoning. Once you've contributed to OTel for a bit, it should be easy for others in the community to make such judgments and sponsor your request.

**Comment by surbhiia** [comment]
Created an issue here - https://github.com/open-telemetry/community/issues/1714

**Comment by arminru** [comment]
Team created and added to CODEOWNERS.
