### ISSUE TITLE
Database/Messaging  extensions: revise extends in yaml 

### ISSUE THREAD

**Issue by lmolkova** [open-telemetry/semantic-conventions#360]
Came up in https://github.com/open-telemetry/semantic-conventions/pull/359#discussion_r1342922914.

UPDATE: based on the discussion in Semconv WG:
- we need to revisit individual database semconv and check if they should `extend` base db conventions in yaml.
- if  some of the recommended generic attributes do not apply to specific DB, extensions should not extend base one and should rather reference all applicable attributes
- based on this we can also restructure generic DB conventions and adjust requirement levels

The context:

Elasticsearch semconv extends `db` in yaml, but re-referenced attributes in the  `server.*` namespace, so it's unclear what was the original intent and what the actually full semconv should be:

**Option 1:**

If Elastic should only report attributes currently defined/referenced in yaml (without extending db), then all the attributes are

`<!-- semconv db.elasticsearch -->`
| Attribute  |
|---|
| `db.elasticsearch.cluster.name` | 
| `db.elasticsearch.node.name` | 
| `db.elasticsearch.path_parts.<key>` | 
| [`db.operation`](database-spans.md) |
| [`db.statement`](database-spans.md) |
| `http.request.method` | 
| [`server.address`](../general/attributes.md) | 
| [`server.port`](../general/attributes.md) |
| [`url.full`](../url/url.md) | 

**Option 2:**

If elasticsearch should extend DB, then it implicitly includes the following attributes (if a **full** MD table is rendered)

`<!-- semconv db.elasticsearch(full) -->`
| Attribute  | 
|---|
| [`db.connection_string`](database-spans.md) |
| `db.elasticsearch.cluster.name` | 
| `db.elasticsearch.node.name` | 
| `db.elasticsearch.path_parts.<key>` | 
| [`db.jdbc.driver_classname`](database-spans.md) | 
| [`db.name`](database-spans.md) | 
| [`db.operation`](database-spans.md) | 
| [`db.statement`](database-spans.md) |
| [`db.system`](database-spans.md) | 
| [`db.user`](database-spans.md) |
| [`network.transport`](../general/attributes.md) | 
| [`network.type`](../general/attributes.md) | 
| [`server.address`](../general/attributes.md) | 
| [`server.port`](../general/attributes.md) | 
| [`server.socket.address`](../general/attributes.md) |
| [`server.socket.domain`](../general/attributes.md) |
| [`server.socket.port`](../general/attributes.md) | 
| [`url.full`](../url/url.md) |

**Comment by lmolkova** [comment]
I believe we should provide all the applicable attributes in the system-specific md tables for all databases and messaging extensions.

It would provide clarify to the readers and instrumentation authors and allow semconv authors to document system-specific things about the attributes.

**Comment by trask** [comment]
@lmolkova is this now a duplicate of #869?

**Comment by lmolkova** [comment]
yes, #869 is wider than this one. Let's close this one.
