### ISSUE TITLE
Publish a first release

### ISSUE THREAD

**Issue by marcalff** [open-telemetry/semantic-conventions#37]
In the past, semantic conventions were released with the specifications, on a regular basis (monthly).

Language repositories, like opentelemetry-cpp, [followed][semconv-cpp] this schedule to release up to date C++ semantic conventions, generated from the specification yaml files.

Now that the semantic conventions moved to this repository, when code gets stable, please make a first release with a tag, so that:
* language repositories can adjust code generations scripts
* language repositories can stay up to date

Please also indicate the expected release frequency for semantic conventions (still monthly ?), so downstream repositories can plan accordingly.

[semconv-cpp]: https://github.com/open-telemetry/opentelemetry-cpp/issues?q=is%3Aissue+semantic+conventions+is%3Aclosed+

**Comment by pellared** [comment]
Do we have proposal how and when the next release will be versioned? Will it be `1.21.0` (as previous version of semconv is `1.20.0`) or will it be `2.0.0`?

PS. I just want to make sure that it will be anything greater than `1.20.0` 😉

**Comment by jsuereth** [comment]
The number *will* be greater than `1.20.0`.

We're still debating between `1.21.1` and `2.0.0`.

Given the HTTP semconv changes, we're waiting for the bulk of "stabilization" changes to land before the next release.

cc @reyang @arminru @trask 

i.e. this next release will be *feature* driven, not time driven.  As such, there's a few blocking issues, like:

- #20 
  This is indicative of a greater issue around naming + metrics, not specific to HTTP
- #43 
- #17

**Comment by jsuereth** [comment]
> Please also indicate the expected release frequency for semantic conventions (still monthly ?), so downstream repositories can plan accordingly.

Once we hit our first release from this repository, we would like to resume monthly releases.  We'll keep you updated.

**Comment by marcalff** [comment]
@jsuereth 

Please consider to add a `VERSION` file in the git repository itself.

When using a tar file from artifacts delivered, the _content_ should contain a version number, not just the tar file name.

Please make the file easy to parse by makefiles, for example:

```
OPENTELEMETRY_SEMCONV_VERSION_STRING=1.21.0
OPENTELEMETRY_SEMCONV_VERSION_MAJOR=1
OPENTELEMETRY_SEMCONV_VERSION_MINOR=21
OPENTELEMETRY_SEMCONV_VERSION_PATCH=0
```

Related to:
* https://github.com/open-telemetry/opentelemetry-proto/issues/434
