### ISSUE TITLE
trace/http: Add semantic convention for total request and response length

### ISSUE THREAD

**Issue by kamalmarhubi** [open-telemetry/semantic-conventions#38]
The current `http.request_content_length ` and `http.response_content_length ` are specified to be the length of the body excluding headers. I'd like to add an attribute for the total message size.

For names, I think `http.request_length` and `http.response_length` make the most sense.

Rationale:
- the seemingly related metrics [`http.server.request.size`](https://opentelemetry.io/docs/specs/otel/metrics/semantic_conventions/http-metrics/#metric-httpserverrequestsize) and [`http.server.response.size`](https://opentelemetry.io/docs/specs/otel/metrics/semantic_conventions/http-metrics/#metric-httpserverresponsesize) are in fact measure of total bytes sent
- some systems only provide the total HTTP message length, eg [Google Cloud Load Balancer logs](https://cloud.google.com/logging/docs/reference/v2/rest/v2/LogEntry#HttpRequest.FIELDS.request_size) and [AWS ALB logs](https://docs.aws.amazon.com/elasticloadbalancing/latest/application/load-balancer-access-logs.html#access-log-entry-format); these are logs, but we process those logs into spans

**Comment by kamalmarhubi** [comment]
Just caught up on the effect of open-telemetry/opentelemetry-specification#3355 which. The ECS names for the fields I'd like are:
- [`http.request.bytes`](https://www.elastic.co/guide/en/ecs/current/ecs-http.html#field-http-request-bytes)
- [`http.response.bytes`](https://www.elastic.co/guide/en/ecs/current/ecs-http.html#field-http-response-bytes)

By analogy with the renamings introduced in that PR, the new attributes should be
- `http.request.size`
- `http.response.size`

**Comment by trask** [comment]
just adding the same heads up here from https://github.com/open-telemetry/semantic-conventions/pull/84#issuecomment-1579282520 (for anyone else viewing the issue):

> the HTTP semantic convention WG isn't considering any additions until the HTTP semantic conventions have at least been marked Frozen, so it may be a few weeks until we get to reviewing this proposal
