### ISSUE TITLE
Use seconds as default duration for DB client metrics

### ISSUE THREAD

**Issue by pyohannes** [open-telemetry/semantic-conventions#381]
This issue was created based on a discussion about #176.

[General guidelines for metric instrumentation units](https://github.com/open-telemetry/semantic-conventions/blob/main/docs/general/metrics.md#instrument-units) require that for measuring durations, seconds should be used:

> * When instruments are measuring durations, seconds (i.e. s) SHOULD be used.

However, the following DB client metrics still use milliseconds for measuring durations:
* [`db.client.connections.create_time`](https://github.com/open-telemetry/semantic-conventions/blob/main/docs/database/database-metrics.md#metric-dbclientconnectionscreate_time)
* [`db.client.connections.wait_time`](https://github.com/open-telemetry/semantic-conventions/blob/main/docs/database/database-metrics.md#metric-dbclientconnectionswait_time)
* [`db.client.connections.use_time`](https://github.com/open-telemetry/semantic-conventions/blob/main/docs/database/database-metrics.md#metric-dbclientconnectionsuse_time)

For consistency, those histograms should be changed to use seconds. Those metrics are already in use, and to avoid unnecessary disruptions the change should happen during stabilization of DB semantic conventions and should be covered by the `OTEL_SEMCONV_STABILITY_OPT_IN` mechanism.

**Comment by trask** [comment]
the initial database semantic convention stability isn't targeting these metrics, but it makes sense to me to make these changes as part of the stability effort so that they can be grouped with the other database semconv breaking changes

**Comment by jack-berg** [comment]
> the initial database semantic convention stability isn't targeting these metrics, but it makes sense to me to make these changes as part of the stability effort so that they can be grouped with the other database semconv breaking changes

I agree. Consumers of db semantic conventions will already be dealing with significant breaking changes. Withholding changes to part of the conventions because they're not targeted for stability is probably detrimental to the user experience.

**Comment by gregkalapos** [comment]
As suggested by @trask https://github.com/open-telemetry/semantic-conventions/pull/966#pullrequestreview-2025811321 doing it in https://github.com/open-telemetry/semantic-conventions/pull/966
