### ISSUE TITLE
Attributes should only have default values if supplying the attribute is (otherwise) required

### ISSUE THREAD

**Issue by trask** [open-telemetry/semantic-conventions#385]
In order to avoid ambiguity between default attribute value and unknown attribute value. 

motivated by @lmolkova's https://github.com/open-telemetry/semantic-conventions/issues/373#issuecomment-1758407649:

> This way, a lack of protocol would mean a lack of information (and not default value)

**Comment by trask** [comment]
It looks like these are the (HTTP) attributes potentially in this boat:

### `network.protocol.name`

https://github.com/open-telemetry/semantic-conventions/blob/b127e121b9b458e83a0fee8a32f7eb6721912951/model/http-common.yaml#L31-L34

### `server.port` (on server side)

https://github.com/open-telemetry/semantic-conventions/blob/b127e121b9b458e83a0fee8a32f7eb6721912951/model/trace/http.yaml#L92-L95

**Comment by trask** [comment]
I'm not sure if we can conditionally require `network.protocol.name` when it's not the default value, since that's a low-level attribute which may not always be capturable(?). It's also not a generally useful piece of data in the scope of HTTP semconv. Maybe it should be opt-in?

For `server.port` (on the server side), it seems like that's pretty accessible to HTTP server instrumentation, so maybe we can change it from `recommended` to `conditionally_required`(?)

**Comment by lmolkova** [comment]
> I'm not sure if we can conditionally require network.protocol.name when it's not the default value, since that's a low-level attribute which may not always be capturable(?). It's also not a generally useful piece of data in the scope of HTTP semconv. Maybe it should be opt-in?

The alternative is to remove `spdy` - it's been [deprecated](https://www.chromium.org/spdy/) and removed from browsers 7+ years ago. Assuming we don't expect spdy, we can remove  `network.protocol.name` from HTTP semconv. 
It de-facto makes it opt-in for any custom instrumentation that wants to capture it.
Backaends can safely assume `http` and it will be inaccurate for those who still use `spdy`. Given they use an deprecated and experimental protocol,things like this should be expected and tolerable.

**Comment by lmolkova** [comment]
> For server.port (on the server side), it seems like that's pretty accessible to HTTP server instrumentation, so maybe we can change it from recommended to conditionally_required(?)

Agree, I'm surprised it's `recomended`

**Comment by Oberon00** [comment]
We might have lost the requirement for the port by mistake, since http.host contained the port as well.
