### ISSUE TITLE
"metric attributes must have namespaces" decision is not documented in the general metrics guidelines

### ISSUE THREAD

**Issue by joaopgrassi** [open-telemetry/semantic-conventions#394]
In https://github.com/open-telemetry/semantic-conventions/issues/51#issuecomment-1604775862 the TC has voted on the matter of "metric attributes must have namespaces" but the actual decision/guidelines never made to the general metric guidelines in https://github.com/open-telemetry/semantic-conventions/blob/main/docs/general/metrics.md

**Comment by pyohannes** [comment]
I guess it's already present in the [general attribute naming guidelines](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/common/attribute-naming.md#attribute-naming)? 

> _This section applies to Resource, Span, Log, and Metric attribute names (also known as the "attribute keys")._ [...]
>
> Names SHOULD follow these rules:
> * Use namespacing to avoid name clashes.

This seems to be related to open-telemetry/opentelemetry-specification#3746: do we see metric naming guidelines as an extension of the general attribute naming guidelines?

**Comment by jsuereth** [comment]
We are currently treating all `SHOULD` guidance as `MUST` for our own semconv definitions.
