### ISSUE TITLE
Sampling relevant attributes: MUST vs SHOULD

### ISSUE THREAD

**Issue by trask** [open-telemetry/semantic-conventions#422]
Related to #319

Currently the HTTP semantic convention says:

> Following attributes MUST be provided **at span creation time** (when provided at all), so they can be considered for sampling decisions:
>
> * [`server.address`](../general/attributes.md)
> * [`server.port`](../general/attributes.md)
> * [`url.full`](../url/url.md)

We have an example where this is not possible: https://github.com/open-telemetry/opentelemetry-dotnet/issues/4830

This may get resolved in .NET 9 (~1 year from now), but I think it's worth discussing MUST vs SHOULD for sampling relevant attributes.

**Comment by trask** [comment]
Discussed in 10/23 semconv meeting and decided to stay with MUST.

**Comment by lmolkova** [comment]
I'm okay changing from MUST to SHOULD, but  the way I read the full sentence "Following attributes MUST be provided **at span creation time** (when provided at all), **so they can be considered for sampling decisions:**" is:
- you MUST provide attributes to be able to access them at sampling time. 
- instrumentation library MUST collect them before the span starts
- instrumentation library that provides a callback to collect sampling relevant attributes MUST do it before starting a span

If these intentions are not clear, let's improve them (and change MUST to SHOULD if it feels better)

**Comment by trask** [comment]
Discussed with @lmolkova and we agreed that it's good to change sampling relevant attributes from `MUST` to `SHOULD`.

* `SHOULD` is already a strong statement (https://datatracker.ietf.org/doc/html/rfc2119):

  > SHOULD - This word, or the adjective "RECOMMENDED", mean that there may exist valid reasons in particular circumstances to ignore a particular item, but **the full implications must be understood and carefully weighed before choosing a different course**.

  and [we expect all HTTP instrumentations published under the OpenTelemetry org to follow SHOULDs](https://github.com/open-telemetry/semantic-conventions/issues/281).

* `MUST` here implies that users who enhance a span with a sampling relevant attribute (e.g. `http.request.header.*`) _after_ start are "breaking compliance with HTTP semantic conventions", while `SHOULD` does not imply "breaking compliance".

**Comment by trask** [comment]
re-opening until we apply the change in this repo
