### ISSUE TITLE
Review requirement level of `server.address` and `server.port` on HTTP server spans

### ISSUE THREAD

**Issue by trask** [open-telemetry/semantic-conventions#424]
#399 makes `server.port` conditionally required

> If not default (`80` for `http` scheme, `443` for `https`).

with the assumption that

> we expect `server.port` to be available to all HTTP server instrumentation.

but this seems inconsistent with the `server.address` requirement level of recommended.

I think it may make sense for `server.address` to be required on HTTP server spans also, given the benefit of backends being able to reconstruct the original URL (not withstanding bogus Host headers). Note however that this would reverse #111.

**Comment by lmolkova** [comment]
Thanks for digging up the context! 

In #111 we discussed that `server.address|port` are not essential on the server side and at least some applications don't need them (the `service.name` may be enough especially between instances of internal microservices).

I'd prefer to keep the door open in the spec and allow users to opt-out of these attributes.

We can keep `server.address` recommended and add another condition for  `server.port` to populate it if `server.address` is populated and when the value is not default.

This way we ensure that in the presence of address, absence of port means default value.
