### ISSUE TITLE
Request to create semconv-{container,k8s}-approvers

### ISSUE THREAD

**Issue by ChrsMark** [open-telemetry/semantic-conventions#427]
I'd like to request creating 2 new approvers groups `semconv-container-approvers` and `semconv-k8s-approvers` (as per suggestion at https://github.com/open-telemetry/semantic-conventions/issues/427#issuecomment-1789252221) that would be responsible for reviewing and maintaining semantic conventions related to the containers' and kubernetess areas respectively.

Folks proposed for that groups / interested:

`semconv-container-approvers`:
- @frzifus 
- @dmitryax 
- @ChrsMark 
- @mx-psi 
- @TylerHelmuth 
- @jinja2
- @mlunadia 
- TBA

`semconv-k8s-approvers`:
- @frzifus 
- @dmitryax 
- @ChrsMark 
- @mx-psi 
- @TylerHelmuth 
- @jinja2
- @dashpole 
- @mlunadia 
- TBA

Related PRs and issues:

- https://github.com/open-telemetry/semantic-conventions/pull/159
- https://github.com/open-telemetry/semantic-conventions/pull/282
- https://github.com/open-telemetry/semantic-conventions/pull/125
- https://github.com/open-telemetry/semantic-conventions/issues/48
- https://github.com/open-telemetry/semantic-conventions/issues/58

**Comment by ChrsMark** [comment]
@dmitryax could you also ping people from the Collector's side that would be interested to join?

@mlunadia would you be interested into joining as well?

**Comment by TylerHelmuth** [comment]
I am interested in joining.  I would also like to nominate @jinja2 who has been a tremendous source of Kubernetes knowledge for the Collector components.

**Comment by ChrsMark** [comment]
Awesome @TylerHelmuth , I have added you both :)!

**Comment by dmitryax** [comment]
Thank you, @ChrsMark!

**Comment by TylerHelmuth** [comment]
Additional releated issue: https://github.com/open-telemetry/semantic-conventions/issues/430

**Comment by jsuereth** [comment]
I think this is a little to broad of a scope.  E.g. are you going to be owning every semconv for technology coming from CNCF, including otel itself?

Let's alter the name to denote some limits, e.g.

- `semconv-container-approvers`: All things container related (not just docker)
- `semconv-k8s-approvers`: All things kubernetes related (but not nomad, e.g.)

I think it makes sense for us to keep the two lists separate even if it's the same set of folks initially.

**Comment by ChrsMark** [comment]
Thank's @jsuereth , that makes sense! I can split the group into 2 different groups then.

**Comment by dashpole** [comment]
I'd like to nominate myself for the k8s-approvers group.

**Comment by mlunadia** [comment]
@ChrsMark yes, please add me in

**Comment by arminru** [comment]
I created @open-telemetry/semconv-container-approvers and added the following members:

@frzifus
@dmitryax
@ChrsMark
@mx-psi
@TylerHelmuth
@jinja2

@mlunadia I was not able to add you as you are not a member of the OpenTelemetry organization yet.
Please review the requirements and application steps described here: https://github.com/open-telemetry/community/blob/main/community-membership.md#member

**Comment by arminru** [comment]
I created @open-telemetry/semconv-k8s-approvers and added the following members:

- @frzifus
- @dmitryax
- @ChrsMark
- @mx-psi
- @TylerHelmuth
- @jinja2
- @dashpole

@mlunadia please see my comment [above](https://github.com/open-telemetry/semantic-conventions/issues/427#issuecomment-1808543791).

**Comment by arminru** [comment]
@open-telemetry/semconv-container-approvers and @open-telemetry/semconv-k8s-approvers you can go ahead and update https://github.com/open-telemetry/semantic-conventions/blob/main/.github/CODEOWNERS to add OWNERS for the relevant subdirectories.

**Comment by ChrsMark** [comment]
Thank's @arminru. I have filed https://github.com/open-telemetry/semantic-conventions/pull/510 to add the CODEOWNERS.

**Comment by mlunadia** [comment]
@arminru I have now my membership and have requested to join. Thanks!

**Comment by mlunadia** [comment]
@arminru just checking if you can add me to the approvers for both of these groups.
TIA

**Comment by arminru** [comment]
Hi @mlunadia!
After the initial bootstrapping of a newly founded group, approvers are expected to satisfy the approver requirements laid out here: https://github.com/open-telemetry/community/blob/main/community-membership.md#approver
Please open an issue if all of these apply so we can add you to the group.
Thanks!
