### ISSUE TITLE
Should HTTP client `server.address` and `server.port` be captured from `Host` header?

### ISSUE THREAD

**Issue by trask** [open-telemetry/semantic-conventions#457]
This would correlate with how `server.address` and `server.port` are captured on the server side.

(though in practice most of the time there's probably no difference)

**Comment by lmolkova** [comment]
There are just two places where host:port could appear on the client side:
- request target
- host header

And they must match:

> [If the target URI includes an authority component, then a client MUST send a field-value for Host that is identical to that
   authority component](https://datatracker.ietf.org/doc/html/rfc7230#section-5.4:~:text=If%20the%20target%20URI%20includes%20an%20authority%20component%2C%20then%20a%0A%20%20%20client%20MUST%20send%20a%20field%2Dvalue%20for%20Host%20that%20is%20identical%20to%20that%0A%20%20%20authority%20component%2C%20excluding%20any%20userinfo%20subcomponent%20and%20its%20%22%40%22%0A%20%20%20delimiter%20(Section%202.7.1))


Also, my educated guess is that Host header is usually set by the HTTP clients internals not reachable by the public -API-level instrumentation. I.e. we probably use URI available through HTTP client public API that later on is translated to Host header.

Asking to use Host header would mean setting it after the request is sent (and we now have updated request object)  and would make it unavailable for sampling and active_requests metrics.
