### ISSUE TITLE
HTTP semantic convention stability countdown

### ISSUE THREAD

**Issue by trask** [open-telemetry/semantic-conventions#480]
Opening this as a planning and tracking issue to coordinate the last few items before we can mark HTTP semantic conventions as stable.

Most important:

- [x] Review, approve, merge build-tools PR: https://github.com/open-telemetry/build-tools/pull/230
- [x] Make new release from build-tools repository

Then finish reviewing, approving, merging these PRs:

- [x] #486
- [x] #467
- [x] #478
- [x] #479

And finally:

- [x] #377

**Comment by arminru** [comment]
Done! See #377 and https://github.com/open-telemetry/semantic-conventions/releases/tag/v1.23.0.
