### ISSUE TITLE
Remove `shared` from `system.memory.state` values?

### ISSUE THREAD

**Issue by trask** [open-telemetry/semantic-conventions#522]
Should `shared` be removed from [`system.memory.state`](https://github.com/open-telemetry/semantic-conventions/blob/main/docs/system/system-metrics.md#metric-systemmemoryusage) values?

I'm reviewing the [`usage` naming convention](https://github.com/open-telemetry/semantic-conventions/blob/main/docs/general/metrics.md#instrument-naming):

> Where appropriate, the sum of **usage** over all attribute values SHOULD be equal to the **limit**.

and at least on my system, the `shared` dimensions appears to be double counted:

```
root@972900a4c455:/# free
               total        used        free      shared  buff/cache   available
Mem:        32847132     2214804    30020716       80216      611612    30172244
```

doing the math:

```
32847132 = 2214804 + 30020716 + 611612
```

cc @open-telemetry/semconv-system-approvers

**Comment by mx-psi** [comment]
Discussed on January 18th System Semantic Conventions WG meeting, similar to #531 this blocks stability

**Comment by ChrsMark** [comment]
Thank's @braydonk! 

@open-telemetry/semconv-system-approvers any thoughts about this?
