### ISSUE TITLE
Publish a new release including the fix applied in #524

### ISSUE THREAD

**Issue by arminru** [open-telemetry/semantic-conventions#533]
Either by cherry-picking 2817a7f onto https://github.com/open-telemetry/semantic-conventions/releases/tag/v1.23.0 and creating a `1.23.1` patch release, or by releasing all pending changes from main as `1.24.0`.

**Comment by arminru** [comment]
PRs merged and patch release published: https://github.com/open-telemetry/semantic-conventions/releases/tag/v1.23.1

**Comment by arminru** [comment]
@open-telemetry/specs-semconv-maintainers what do you think about this?

> The fix PR (#524) was cherry-picked from main already but the changelog update and patched schema file from this PR will only be on `release/v1.23.x` and tag `v1.23.1` for now.
> 
> I was thinking of copying them over to `main` so users can see everything at in one place but I will check with the other @open-telemetry/specs-semconv-maintainers if they agree.

_Originally posted by @arminru in https://github.com/open-telemetry/semantic-conventions/issues/538#issuecomment-1816529758_

**Comment by joaopgrassi** [comment]
The release using the "patch version" approach is published https://github.com/open-telemetry/semantic-conventions/releases/tag/v1.23.1. The OTel website is also updated and the schema is also live: https://opentelemetry.io/schemas/1.23.1. Closing this as completed.

**Comment by arminru** [comment]
We still need to clarify if we want to copy both changes to the main branch (and subsequently future releases) too:

https://github.com/open-telemetry/semantic-conventions/issues/533#issuecomment-1816678663

cc @open-telemetry/specs-semconv-maintainers
