### ISSUE TITLE
Semantic conventions for go runtime metrics

### ISSUE THREAD

**Issue by dashpole** [open-telemetry/semantic-conventions#535]
For runtime semantic conventions, we currently only have JVM metrics defined: https://github.com/open-telemetry/semantic-conventions/tree/main/docs/runtime#semantic-conventions-for-runtime-environment.  The Go SIG (discussed on 11/16/23) would like to agree on conventions in this repository before expanding the set of metrics offered by the go runtime instrumentation package: https://pkg.go.dev/go.opentelemetry.io/contrib/instrumentation/runtime#pkg-overview to minimize the churn to users.

Additional context:

* There is a separately maintained (thanks @jmacd!) package for go runtime metrics with an expanded set of supported metrics that may also help inform these conventions: https://github.com/lightstep/otel-launcher-go/tree/main/lightstep/instrumentation/runtime

Starting Questions/potential issues:

* Which metrics from the go runtime are stable?  What are the stability guarantees?
* Which metrics should be on-by-default?  Go is possibly considering recommending a default set: https://github.com/golang/go/issues/57175#issuecomment-1804230372.
* Go runtime metrics are currently named `runtime.go.*`, which conflicts with the runtime metrics guidance: `Metrics specific to a certain runtime environment should be prefixed with the runtime's top-level namespace {environment}.*, e.g., jvm.* `

@MrAlias @pellared

**Comment by trask** [comment]
> Which metrics from the go runtime are stable? What are the stability guarantees?

in case the prior art helps, we are putting the breaking JVM metrics changes that we are implementing as part of JVM metric stability behind `OTEL_SEMCONV_STABILITY_OPT_IN=jvm` (and will make them the default in upcoming Java Instrumentation 2.0)
