### ISSUE TITLE
Replace `db.mssql.instance_name` and `db.elasticsearch.node.name` with `db.instance.id`

### ISSUE THREAD

**Issue by AlexanderWert** [open-telemetry/semantic-conventions#542]
Once, https://github.com/open-telemetry/semantic-conventions/pull/345 is merged, we should replace `db.mssql.instance_name` and `db.elasticsearch.node.name` with the new, more generic attribute `db.instance.id`.

**Comment by joaopgrassi** [comment]
Moved this to the database semconv project board
