### ISSUE TITLE
Some links still point to the `main` branch in the spec repo

### ISSUE THREAD

**Issue by patrickhousley** [open-telemetry/semantic-conventions#549]
In a [recent change](https://github.com/open-telemetry/semantic-conventions/pull/473) to the events conventions, discussions were had to update a link from pointing to a specific version/branch of the semantic conventions repository to point to the main branch instead. In discussion on the client-side SIG, we agreed that the link should point to the main branch. While that PR was updated, this repository has many other links that follow suite and need to be updated to point to main instead of a specific version.

Relavent Discussions:
https://github.com/open-telemetry/semantic-conventions/pull/473#discussion_r1399462589
https://github.com/open-telemetry/semantic-conventions/pull/473#discussion_r1400831343

**Comment by patrickhousley** [comment]
Links are in fact supposed to point to a specific version of the semantic conventions repository. There are a handful of links in the repo that do not meet that requirement.

**Comment by joaopgrassi** [comment]
Thanks, I sent a PR to fix the wrong links.
