### ISSUE TITLE
Keep renamed/removed experimental attributes as deprecated

### ISSUE THREAD

**Issue by lmolkova** [open-telemetry/semantic-conventions#550]
When renaming/removing an attribute, we need to preserve the old name in the yaml. 

Currently it disappears, meaning that:
- codegen does not generate it from yaml
- semconv lib maintainers need to manually copy them back to avoid breaking API changes
  -  This creates a lot of work for  language SIGs
     - https://github.com/open-telemetry/semantic-conventions-java/issues/5
     - or [here's how python list](https://github.com/lmolkova/opentelemetry-python/blob/30713b4823587daee76bf5808e1261224e5a6850/scripts/semconv/templates/semantic_attributes.j2#L51-L357) of manually defined deprecated attributes looks like
- OR semconv libraries drop removed attributes from API surface
  - applications that don't have all the versions of instrumentation libraries perfectly aligned can fail in runtime because of missing attributes in newer versions.

Options:

1. Never remove an attribute, when renaming always add the old one to deprecated ones
    - we'd also need CI checks to validate 
2. Add build-tools feature to compare list of attributes between semconv vOld and vNew and generate list of removed attributes.

**Comment by lmolkova** [comment]
My preference would be on Option 2 since we need to build validation tooling anyway, so why not automate the whole process.

**Comment by AlexanderWert** [comment]
@lmolkova For HTTP we have (at some of them) the deprecated attributes listed in a separate section in the registry: https://opentelemetry.io/docs/specs/semconv/attributes-registry/http/#deprecated-http-attributes

I like to have this documented not only in yaml files (and codegen) but also in the docs.

**Comment by lmolkova** [comment]
@AlexanderWert we've been inconsistent with marking them as deprecated. 
So either we embrace it and pick option2 or add tooling to ensure we mark removed ones as deprecated (option1). 

I agree that having them preserved in the spec (at least for a certain period of time) is great.

**Comment by lmolkova** [comment]
closing in favor of #740
