### ISSUE TITLE
Mark initial set of JVM runtime semantic conventions stable

### ISSUE THREAD

**Issue by jack-berg** [open-telemetry/semantic-conventions#552]
All tasks on the [project board](https://github.com/orgs/open-telemetry/projects/49) have been completed. (The only open issue is #519, which I don't think we should address.)

The [1.32.0](https://github.com/open-telemetry/opentelemetry-java-instrumentation/releases/tag/v1.32.0) release of `opentelemetry-java-instrumentation` contains opt-in implementations of the new conventions by setting `OTEL_SEMCONV_STABILITY_OPT_IN` to `jvm` or `jvm/dup`.

Is anything else required before marking the initial set of jvm runtime conventions (i.e. all except those marked [very experimental](https://github.com/open-telemetry/semantic-conventions/blob/main/docs/runtime/jvm-metrics.md#very-experimental))?

**Comment by jack-berg** [comment]
Corresponding PR in `opentelemetry-java-instrumentation`: https://github.com/open-telemetry/opentelemetry-java-instrumentation/issues/9007

**Comment by joaopgrassi** [comment]
Giving #569  was merged, I think this should be closed, no? CC @jack-berg

**Comment by jack-berg** [comment]
Yup this is complete! Closing.
