### ISSUE TITLE
Is possible to align `process.cpu.time,utilization`  metrics defintion to `system.cpu.time,utilization`

### ISSUE THREAD

**Issue by david-luna** [open-telemetry/semantic-conventions#563]
**What are you trying to achieve?**

I've noticed these metrics are quite similar since they are measuring the same but process has a smaller scope. There is only a couple of differences.
- Process metrics have no prefix in their attribute names
System metrics are using `system.cpu.state` & `system.cpu.logical_number` and process is using `state` as attribute name
System ref: [system-metrics.md](https://github.com/open-telemetry/semantic-conventions/blob/main/docs/system/system-metrics.md#metric-systemcputime)
Process ref: [process-metrics.md](https://github.com/open-telemetry/semantic-conventions/blob/main/docs/system/process-metrics.md#process)

- Process metrics have a constraint about labels whereas system metrics doesn't have it
```
A process SHOULD be characterized either by data points with no state labels, or only data points with state labels.
```

What did you expect to see?

IMHO aligning the semantic conventions makes sense. I'd propose to make process metrics conventions closer to system metrics conventions by
- adding prefix on the `state` attribute and becoming `process.cpu.state`
- removing the constraint mentioned above

**Additional context.**

System metrics semconv had a recent change which added prefixes
https://github.com/open-telemetry/semantic-conventions/pull/89

Maybe this something that is planned also fro process and hardware metrics? I could help on that

**Comment by yurishkuro** [comment]
transferred

**Comment by david-luna** [comment]
While looking for references I came across this issue about cardinality  https://github.com/open-telemetry/opentelemetry-js-contrib/issues/1700

I guess this is why we want to have the option of not sending `*.cpu.state` labels.

**Comment by mx-psi** [comment]
Discussed on January 18th System Semantic Conventions WG meeting, adding this as a blocker since it would potentially change attribute names

**Comment by ChrsMark** [comment]
Reading the constraint `A process SHOULD be characterized either by data points with no state labels, or only data points with state labels` I understand how it makes sense being specific for the `process`. However, I wonder if the same constraint could be applied to the `system.cpu.state` which is more generic for the whole system.

@open-telemetry/semconv-system-approvers what do you think?

**Comment by ChrsMark** [comment]
Discussed on February 22th System Semantic Conventions WG meeting, and we agree that it makes sense to do the alignment and add the constraint for `system.cpu.state` as well. I will try to file a PR soon for this.
