### ISSUE TITLE
Semantic Conventions - Append Only?

### ISSUE THREAD

**Issue by bobstrecansky** [open-telemetry/semantic-conventions#568]
We were discussing it in our SIG meeting today.  Will there ever be a point in this project where semantic conventions are not deleted, only added?  Wanted to understand the long term data plan for semantic conventions.

cc:\ @open-telemetry/php-maintainers

**Comment by joaopgrassi** [comment]
@bobstrecansky 

> Will there ever be a point in this project where semantic conventions are not deleted, only added

Yes, that was the intention, but now there's a formal proposal for it. You can follow it here: https://github.com/open-telemetry/semantic-conventions/issues/740

If it's ok with you, I will close this as I feel this has answered your question. :)
