### ISSUE TITLE
Remove abbreviation of kubernetes in resource semantic conventions

### ISSUE THREAD

**Issue by mlunadia** [open-telemetry/semantic-conventions#58]
The current specification for kubernetes resources is `k8s.*`

While `k8s` is a popular abbreviation within the Kubernetes community, using the full name `kubernetes` is preferable in most situations to ensure clear communication and alignment with standard practices.

There is a lot of scope to expand into further fields for semantic conventions for `kubernetes` and whilst there are a few fields it may be practical to consider removing the abbreviation given the below reasons:

1. Clarity: Using "Kubernetes" ensures clarity and avoids confusion compared to the abbreviation "k8s" which not everybody might be familiar with.
3. Standard Terminology: "Kubernetes" is the recognized and widely used name for the platform.
5. Consistency: Using "Kubernetes" maintains consistency in discussions and documentation.
7. Searchability: "Kubernetes" yields more accurate search results when seeking information.
9. Professionalism: Using the full name demonstrates professionalism and adherence to standards.

**Comment by ChrsMark** [comment]
FYI, if we decide to replace `k8s` with `kubernetes` it would need a transition plan on the collector's side as well: https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/receiver/kubeletstatsreceiver/documentation.md

**Comment by TylerHelmuth** [comment]
This would be an incredibly impactful change. If we were to move forward with something like this we will need a plan as robust as the ECS http change.

I do also want to callout that this is not the naming standard in use by KubeStateMetrics, which uses `kube`: https://github.com/kubernetes/kube-state-metrics/blob/main/docs/pod-metrics.md.

**Comment by mlunadia** [comment]
Thank you all for the input, and fair comments. Agree that either is acceptable. 
Closing this issue to convey agreement on k8s
