### ISSUE TITLE
Request to create semconv-security-approver

### ISSUE THREAD

**Issue by trisch-me** [open-telemetry/semantic-conventions#580]
Hi everyone, I would like to create a group `semconv-security-approver` for all PRs related to security fields in following namespaces (some of them are not present now(*) but will be added soon):
- process
- tls
- dll*
- dns*
- file*
- registry*
- user*
- vulnerability*
- x509 Certificate*
- threat*
- and more namespaces to come into security field...

Please add @trisch-me to the group and let's keep this issue open until we have a quorum for this approvers group

Also please let me know if I need to create a project in addition to group.

**Comment by arminru** [comment]
For reference: See https://github.com/open-telemetry/community/pull/1838 for the pending project proposal.

**Comment by trisch-me** [comment]
@joaopgrassi @joaopgrassi should we proceed with this approver group for those namespaces we already have?
i.e. process, tls, file? User and rule are coming soon as well

**Comment by joaopgrassi** [comment]
Hum good question. Not sure if we need the project to be merged first for creating the groups or if the groups can be created already. Never got much involved into the github management things. I will ask the other maintainers.

**Comment by danielgblanco** [comment]
The project has now been approved and merged! 🎉  That should unblock this

**Comment by danielgblanco** [comment]
However, for future reference, issues for GH team creation and membership are normally handled in the https://github.com/open-telemetry/community repo.

**Comment by trisch-me** [comment]
@danielgblanco I saw Issues and PRs in this repo for previous groups, for example https://github.com/open-telemetry/semantic-conventions/pull/510/, https://github.com/open-telemetry/semantic-conventions/issues/294, https://github.com/open-telemetry/semantic-conventions/issues/529

**Comment by trask** [comment]
Creating GitHub teams can only be done currently by Technical Committee members. Some of the maintainers of this repo are TC members so it has kind of worked, but it's probably better in the future to follow the process other SIGs use and open a community issue where any TC member can pick up and create the team.

**Comment by trisch-me** [comment]
should I move it then to the other repo? 
@trask @danielgblanco ?

**Comment by trask** [comment]
I'd open a new "repository maintenance" community issue scoped just to creating the team and listing the members, check out https://github.com/open-telemetry/community/issues/1964

**Comment by trisch-me** [comment]
closing this one in favor of https://github.com/open-telemetry/community/issues/2100
