### ISSUE TITLE
1.23.1 schema is not published

### ISSUE THREAD

**Issue by pellared** [open-telemetry/semantic-conventions#584]
https://opentelemetry.io/schemas/1.23.1 is not available (the schema for https://github.com/open-telemetry/semantic-conventions/releases/tag/v1.23.1).

https://github.com/open-telemetry/semantic-conventions/tree/main/schemas does not contain the schema for `1.23.1`.

This issue blocks: https://github.com/open-telemetry/opentelemetry-go/issues/4745

**Comment by tigrannajaryan** [comment]
We had checks that should have prevented releases when the corresponding schema file does not exist. Not sure why this was not caught.
