### ISSUE TITLE
Add recommendation that attribute keys should be lowercase

### ISSUE THREAD

**Issue by arminru** [open-telemetry/semantic-conventions#586]
In https://github.com/open-telemetry/opentelemetry-specification/issues/3782 it was brought up that the (de-facto) case sensitivity of attribute keys is not documented. A clarification on that will likely be added to the spec (https://github.com/open-telemetry/opentelemetry-specification/pull/3784).

In our attribute naming guidelines at https://github.com/open-telemetry/semantic-conventions/blob/main/docs/general/attribute-naming.md#attribute-naming, we do not cover casing. It is implied to some extent since all examples are lowercase and so are all currently defined keys in semantic conventions, but we might want to call that out explicitly.

**Comment by joaopgrassi** [comment]
I opened a PR for it https://github.com/open-telemetry/semantic-conventions/pull/788
