### ISSUE TITLE
[messaging] Should we use deliver and receive spans together?

### ISSUE THREAD

**Issue by alevenberg** [open-telemetry/semantic-conventions#590]
Discussed today in messaging working group.

Currently it is undefined to include both receive and deliver spans in the spec.

In the current spec, we would want both receive and deliver spans.

Maybe reconsider the process span semantics.

cc @lmolkova @feywind @hongalex @pyohannes

**Comment by pyohannes** [comment]
This was discussed in the last workgroup meeting.

Currently, the semantic conventions don't forbid the existence of both "receive" and "deliver" spans for the consumption of a single message. We also don't want to add such a restriction, as in some circumstances it's impossible to realize. For example a messaging abstraction layer like JMS or MassTransit might not know whether the underlying messaging SDKs that are used already created a "receive" or "deliver" span (or no span at all), and thus cannot ensure the exclusivity.

Generally, for push-based consumption scenarios, alongside the "deliver" span there can be a "receive" span, which models mechanisms of receiving and buffering messages which are internal to the SDK and not transparent to the user. However, library authors are certainly free to instrument those operations, we don't want the semantic conventions to make assumptions or requirements about this instrumentation.
