### ISSUE TITLE
The compatibility issue caused by the changes of attribute names of semantic conventions

### ISSUE THREAD

**Issue by liurui-1** [open-telemetry/semantic-conventions#623]
There are so many changes of attribute names of semantic conventions, for example: trace span attribute `http.method` is changed to `http.request.method`, for example the attribute `state` of metric "system.cpu.time" (of system)  is changed to `system.cpu.state` ... I have not found that auto-instrumentation implementations or OpenTelemetry Collector follows those new changes which can cause a lot of compatibility issues. 

Those changes have caused a lot of new issues:
- New vendors are facing difficulties to support OpenTelemetry because they do not know which convention to follow. 
- Some vendors do not follow any convention because the convention is not stable. For example Java Spring framework native OTel does not provide span attributes required by the Semantic Convention.

It seems that you prefer to use more and more specific names for the attribute but the bad thing about it is that it can make it more difficult to use cross query statements.

Do you have any comments for this issue?

**Comment by trask** [comment]
hi @liurui-1! HTTP semantic conventions were [recently declared stable](https://opentelemetry.io/blog/2023/http-conventions-declared-stable/), and all implementations are recommended to adopt the stable version.
