### ISSUE TITLE
Checklist for declaring stability for messaging semantic conventions

### ISSUE THREAD

**Issue by pyohannes** [open-telemetry/semantic-conventions#646]
### Separate experimental parts from stable messaging semantic conventions

When messaging semantic conventions are declared stables, some parts of the conventions should be excluded and remain in an experimental state.

This issue collects all parts that should be marked as experimental prior to declaring messaging semantic conventions stable:

* All references to "Process" spans (open-telemetry/semantic-conventions#657)
* All references to "Settle" spans (open-telemetry/semantic-conventions#621)
* The following attributes:
  - `messaging.message.body.size` (open-telemetry/semantic-conventions#474)
  - `messaging.message.envelope.size` (open-telemetry/semantic-conventions#474)
  - `network.protocol.name` (open-telemetry/semantic-conventions#504)
  - `network.protocol.version` (open-telemetry/semantic-conventions#504)
  - `messaging.destination.temporary` and `messaging.destination.anonymous` (open-telemetry/semantic-conventions#1126)

Finally, also any stability present on any stabilized messaging documents need to be removed.

### Open tickets against instrumentations

As suggested in [this comment](https://github.com/open-telemetry/semantic-conventions/pull/734#discussion_r1486279520), tickets against all existing messaging instrumentations in OpenTelemetry repositories need to be opened, outlining the changes and required actions

**Comment by joaopgrassi** [comment]
The last item in this list was done https://github.com/open-telemetry/semantic-conventions/pull/1442, so closing this one.
