### ISSUE TITLE
The protocol attribute should be removed for `system.network.connections` metrics

### ISSUE THREAD

**Issue by codeboten** [open-telemetry/semantic-conventions#649]
**What are you trying to achieve?**

Since UDP has no state, I propose UDP and TCP connection metrics should be split into protocol specific metric for each supported protocol. 

If folks agree, I will open a PR to mark system.network.connections as deprecated in favour of:

`system.network.tcp.connections`
`system.network.udp.connections`

**Additional context.**

The work for this was previously done in https://github.com/open-telemetry/opentelemetry-specification/pull/2675 and reverted in https://github.com/open-telemetry/opentelemetry-specification/pull/2748. See https://github.com/open-telemetry/opentelemetry-specification/issues/2726 for additional context

**Comment by mx-psi** [comment]
@codeboten Can you help us with the question above?

**Comment by codeboten** [comment]
With the recommendation to not set the `state` attribute for stateless protocols, this is probably ok to close
