### ISSUE TITLE
Track specification-related changes required for stabilizing messaging semantic conventions

### ISSUE THREAD

**Issue by pyohannes** [open-telemetry/semantic-conventions#659]
This issue tracks specification-related changes which are needed to declare messaging semantic conventions stable. It needs to be ensured that all of those are resolved before declaring stability.

* [x] https://github.com/open-telemetry/opentelemetry-specification/issues/2176
* [x] https://github.com/open-telemetry/opentelemetry-specification/issues/3172
* [x] https://github.com/open-telemetry/opentelemetry-specification/issues/3847
* [x] https://github.com/open-telemetry/opentelemetry-specification/issues/3865

**Comment by joaopgrassi** [comment]
Given all tasks in the issue here are finished, I'm closing this.
