### ISSUE TITLE
Protocol negotiation and ambiguity of `network.protocol.version`

### ISSUE THREAD

**Issue by lmolkova** [open-telemetry/semantic-conventions#686]
Related to https://github.com/dotnet/docs/pull/39223#issuecomment-1921952735 and https://github.com/dotnet/runtime/issues/97395#issuecomment-1924402372

During network protocol negotiation there are two protocol versions:
- one that client requested originally 
- one that was agreed upon during negotiation

If response was received at all, then it makes total sense to set `network.protocol.version` to the final version.
If response was not received, we can set the `network.protocol.version` to the request version (which might be misleading or not useful since it's at least sometimes per-client configuration)

So we:
- need to update `network.protocol.version` description to clarify that it's the negotiated version 
- need to decide if we want to fallback to request/initial version if no response was received

**Comment by trask** [comment]
> since it's at least sometimes per-client configuration

I didn't follow this part, can you explain a bit more?

**Comment by lmolkova** [comment]
> I didn't follow this part, can you explain a bit more?

On the request side, protocol is frequently a client property:
- [.NET HttpClient](https://learn.microsoft.com/en-us/dotnet/api/system.net.http.httpclient.defaultrequestversion?view=net-8.0)
- [okhttp](https://javadoc.io/doc/com.squareup.okhttp3/okhttp/3.14.9/okhttp3/OkHttpClient.Builder.html#protocols-java.util.List-)
- [Reactor-netty](https://projectreactor.io/docs/netty/release/api/reactor/netty/http/client/HttpClient.html#protocol-reactor.netty.http.HttpProtocol...-)

It's interesting that okhttp and netty allow to pass an array of supported protocols reiterating the point  that request protocol version is somewhat useless.

The only benefit of falling back to request protocol version I see is when the client sends bad protocol version and/or server fails to respond to it. Then having requested version on the telemetry would be interesting.

**Comment by joaopgrassi** [comment]
> The only benefit of falling back to request protocol version I see is when the client sends bad protocol version and/or server fails to respond to it. Then having requested version would be interesting.

Wouldn't the HTTP client log messages, maybe containing the requested protocol version? I feel this is more a job of a log than recording this info in a span or somewhere else 🤔

**Comment by trask** [comment]
It definitely simplifies things if we simply clarify that `network.protocol.version` is the negotiated version

**Comment by joaopgrassi** [comment]
Who will do the honors with a PR? ✨

**Comment by lmolkova** [comment]
Adding it here so we wont forget 

> When addressing https://github.com/open-telemetry/semantic-conventions/issues/520/https://github.com/open-telemetry/semantic-conventions/issues/686 we this text needs to be manually updated in dotnet-http-metrics.md.

https://github.com/open-telemetry/semantic-conventions/pull/801#discussion_r1522228909

I can do the PR after #801 is merged.
