### ISSUE TITLE
Semantic Convention responsability clarification

### ISSUE THREAD

**Issue by smoms** [open-telemetry/semantic-conventions#689]
Am I correct that - and especially for logs ( I am using .NET) - the Semantic Convention  in a log record is in the responsability of the application for defining/adding such fields?

For example, for exceptions there are fields like [exception.message](https://github.com/open-telemetry/semantic-conventions/blob/main/docs/attributes-registry/exception.md) and [exception.stacktrace](https://github.com/open-telemetry/semantic-conventions/blob/main/docs/attributes-registry/exception.md).
I do understand that in the OpenTelemetry .NET SDK there is NO such out-of-box parameters, right? Yet. it is recommended that applications add such fields following the Semantic Convention. I've read the documentation but I would like to be sure of my understadning.

thanks.

**Comment by trask** [comment]
hi @smoms! I don't believe you should be populating `exception.message` or `exception.stacktrace` yourself. I believe the .NET logging framework -> OpenTelemetry log bridge should be automatically populating those fields.

But I'm not familiar with the specifics in .NET so tagging @open-telemetry/dotnet-approvers

**Comment by gregkalapos** [comment]
By looking at the [source code of the .NET client for logs](https://github.com/open-telemetry/opentelemetry-dotnet/tree/main/src/OpenTelemetry/Logs), I don't think the .NET implementation tries to comply to the current spec. I don't see it setting any of the `exception` attributes.

It does [capture the exception](https://github.com/open-telemetry/opentelemetry-dotnet/blob/main/src/OpenTelemetry/Logs/ILogger/OpenTelemetryLogger.cs#L70), and uses [it to set the `OriginalFormat`](https://github.com/open-telemetry/opentelemetry-dotnet/blob/main/src/OpenTelemetry/Logs/ILogger/OpenTelemetryLogger.cs#L85-L98) - the result of this can be seen in the snippet above from @smoms. But I don't think it does anything more than that.

I wonder, should this issue be transferred to https://github.com/open-telemetry/opentelemetry-dotnet and then maybe discuss to set those specified `exception` attributes according to the spec in the .NET implementation?

**Comment by alanwest** [comment]
👋 Hi @smoms, I'm from the opentelemetry-dotnet project. Please do open an issue there as this is .NET specific.

Some additional context...

> I don't believe you should be populating exception.message or exception.stacktrace yourself. I believe the .NET logging framework -> OpenTelemetry log bridge should be automatically populating those fields.

Trask is correct that this is ideally how things should work, but it is not quite how .NET ILogger instrumentation works at the moment. The exception is captured but it is not captured as attributes on the log record. Currently, this responsibility falls on each individual exporter to handle how the exception will be represented.

In your example, the console exporter writes it out as
```
LogRecord.Exception:               System.DivideByZeroException: Attempted to divide by zero.
```

If you were to use the OTLP exporter, it [transforms the exception to the appropriate attributes](https://github.com/open-telemetry/opentelemetry-dotnet/blob/05700f640a26b813d4d2e63908fbac45c21a7a6e/src/OpenTelemetry.Exporter.OpenTelemetryProtocol/Implementation/OtlpLogRecordTransformer.cs#L144-L149).

**Comment by smoms** [comment]
@alanwest thanks for the message. I'll open it there.

What I am wondering though is that I am using OTel Exporter too. And in Grafan I still do not see those fields:

```
logger.LogError(ex, "You shall not divide by 0");
logger.Log(LogLevel.Error, ex.ToString());
```


```
2024-02-09 12:15:47.005	
{
  "body": "You shall not divide by 0",
  "traceid": "a9b25c950fcadf6bc37ad7a88af58cfc",
  "spanid": "67687d1a30e805fd",
  "severity": "Error",
  "flags": 1,
  "resources": {
    "service.instance.id": "38033f53-0fb8-490c-8261-c2c050a0def9",
    "service.name": "myService",
    "service.namespace": "myNs",
    "service.version": "1.0.0",
    "telemetry.sdk.language": "dotnet",
    "telemetry.sdk.name": "opentelemetry",
    "telemetry.sdk.version": "1.7.0"
  },
  "instrumentation_scope": {
    "name": "Program"
  }
}
```
