### ISSUE TITLE
Database errors in metrics

### ISSUE THREAD

**Issue by careless6666** [open-telemetry/semantic-conventions#693]
Now the convention only has success metrics
https://github.com/open-telemetry/semantic-conventions/blob/main/docs/database/database-metrics.md

How about adding a label about the error or new metric?

The error can occur both when opening a connection and when executing a request (command)

**Comment by lmolkova** [comment]
Now that we have generic `error.type` attribute, we should be able to address it.

**Comment by jack-berg** [comment]
Does `error.type` make sense for any of the existing metrics? It seems like no. I do think `error.type` makes sense for the client operation duration metric proposed in #512.

**Comment by careless6666** [comment]
Yes, that's what I need
