### ISSUE TITLE
Add db.statement sanitization/masking examples

### ISSUE THREAD

**Issue by mateuszrzeszutek** [open-telemetry/semantic-conventions#708]
**What are you trying to achieve?**

The [trace DB spec](https://github.com/open-telemetry/opentelemetry-specification/blob/master/specification/trace/semantic_conventions/database.md#call-level-attributes) mentions that the `db.statement` attribute value `may be sanitized to exclude sensitive information` but provides no example of such sanitization.
The aim of this issue is to add several examples of how we should sanitize database statements, e.g. `INSERT INTO payment_cards (CC, EXP_DATE) values (?, ?)` for SQL or `HMSET cards cc ? exp_date ?` for Redis.

**Additional context.**

See: https://github.com/open-telemetry/opentelemetry-java-instrumentation/pull/1405

**Comment by trask** [comment]
Rolling this issue into #717
