### ISSUE TITLE
Semantic Conventions for MongoDB

### ISSUE THREAD

**Issue by toumorokoshi** [open-telemetry/semantic-conventions#709]
**What are you trying to achieve?**

Reach a conclusion on what fields to expose for MongoDB, on top of the existing ones.  

Standardizing on the right keys would be great, but I don't have a specific proposal in mind. Just raising the thread in case anyone has a perspective.

**Additional context.**

Here's a couple examples of Mongo instrumentation:

- The [Python PyMongo instrumentation](https://github.com/open-telemetry/opentelemetry-python/pull/1354) stores the operation and request id.
- The [Java instrumentation](https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/master/instrumentation/mongo/mongo-common/src/main/java/io/opentelemetry/javaagent/instrumentation/mongo/MongoClientTracer.java#L43) doesn't set a lot of attributes, But it [may be possible extract more](https://mongodb.github.io/mongo-java-driver/3.6/javadoc/).

**Comment by trask** [comment]
I believe this can be closed, as this is very old and we have both generic database semantic conventions and mongodb semantic conventions now
