### ISSUE TITLE
DB/messaging: stability for specific systems extensions and instrumentation libraries

### ISSUE THREAD

**Issue by lmolkova** [open-telemetry/semantic-conventions#721]
When declaring stability for generic DB/messaging semantic conventions, should we also pick a set of systems and their extended semconv to declare stable or keep them experimental?

If we do stabilize specific systems:
- how do we pick?
- how do we validate (do we need experts/owners of specific systems?)

If we don't stabilize specific systems at the same time:
- we can't stabilize any specific-system instrumentation libraries because of
  - adding custom attributes on metrics will be breaking https://github.com/open-telemetry/semantic-conventions/pull/687
  - spans without custom attributes are not that useful
- it makes overall semconv stability questionable since we aren't confident it's ready to be implemented for specific systems.

**Comment by alanwest** [comment]
> adding custom attributes on metrics will be breaking

I've wanted to understand this better in general. Opened a separate issue https://github.com/open-telemetry/semantic-conventions/issues/722

**Comment by pyohannes** [comment]
A related question crossing my mind: what about messaging and database systems for which no system-specific conventions exists (looking at the values for `db.system`, there could be a lot)? Would those be able to add additional (unspecified) attributes and release a stable version? If so, would a change in those unspecified attributes be considered a breaking change?

**Comment by lmolkova** [comment]
Options to get around breaking changes:
1. Since `messaging.system = {system}` stays experimental, everything produced with this value stays experimental and can have breaking changes
2.  Metric names can include system but follow generic semconv resulting in `messaging.{system}.operation.duration`. The drawback is that common service level metrics would be different and not simply shareable.

The key blocker is instrumentation libraries stability:  if we don't stabilize specific extension, its instrumentation librarires can't go stable.

**Comment by trask** [comment]
Is this resolved now that we have stability per enum value? (We can have separate issues to decide which enum values to include in the initial stabilization efforts, e.g. #965)

**Comment by lmolkova** [comment]
I think this one can be closed. I believe we settled on:
- we do need to stabilize some of the extensions along with the common part
- we need stable common + stable extension (if any) to stabilize instrumentation library
- we'll end up with generic metrics, but any open questions can still be tracked in #553
