### ISSUE TITLE
Is `db.connection_string` necessary?

### ISSUE THREAD

**Issue by lmolkova** [open-telemetry/semantic-conventions#724]
Connection strings can have secrets and have very specific format which makes them not that useful for visualization tooling (or user queries). 
They can also be long and redundant on every span.

They can (secrets redacted) be useful to log to help investigate configuration issues, but probably should not appear on spans/metrics.

Proposal is to remove the attribute or make it opt-in.

**Comment by trask** [comment]
@open-telemetry/java-instrumentation-approvers do you know of anything important being done with `db.connection_string` that we are capturing in Java instrumentation?

**Comment by lmolkova** [comment]
Looking into https://github.com/search?q=repo%3Aopen-telemetry%2Fopentelemetry-java-instrumentation+db_connection_string&type=code&p=1, it seems database instrumentation either  don't set connection string or set driver:schema://host:port. 

host and port are covered with `server.address|port` and we can record schema with `url.scheme` (maybe for specific systems)?
 We can also introduce attribute for driver (when applicable)

**Comment by joaopgrassi** [comment]
Maybe we should ping other maintainers here to get a final opinion?

**Comment by trask** [comment]
cc @open-telemetry/go-approvers @open-telemetry/javascript-approvers @open-telemetry/python-approvers @open-telemetry/opentelemetry-python-contrib-approvers @open-telemetry/dotnet-approvers @open-telemetry/dotnet-contrib-approvers

**Comment by pellared** [comment]
Connection strings can have passwords. 

Example from Go:  https://github.com/go-sql-driver/mysql/?tab=readme-ov-file#dsn-data-source-name

Example from .NET: https://learn.microsoft.com/en-us/dotnet/framework/data/adonet/connection-string-syntax

**Sometimes** the libraries have connection string parsing function that could allow redacting. I think it should be **at least** opt-in.

**Comment by breedx-splk** [comment]
We think that changing the default behavior to omit/exclude the `db.connection_string` attribute will cause immediate degradation of some of our product features.  My preference would be to have the default include the attribute but somehow scrub passwords.

**Comment by trask** [comment]
@breedx-splk can you provide a bit more details about how you are using `db.connection_string`? thanks

**Comment by trask** [comment]
also, is this only for Java customers, or includes other languages as well?

**Comment by pichlermarc** [comment]
I'd also prefer to drop `db.connection_string` or make it opt-in.

As mentioned [above](https://github.com/open-telemetry/semantic-conventions/issues/724#issuecomment-1940433648), in js-contrib we re-construct connection strings from other data that's added to the span already (host, port, db name). 

I just reviewed all of our usages, and I think 100% of the data we add via the `db.connection_string` attribute is redundant.

**Comment by lmolkova** [comment]
@breedx-splk is there some specific information that you get from the connection string that's not available via other attributes?
If so, we can try to capture that information directly and/or document event/log that captures (scrubbed) connection string.

**Comment by breedx-splk** [comment]
> @breedx-splk can you provide a bit more details about how you are using `db.connection_string`? thanks

Sure, yeah. From what I understand, our APM UI leverages the `db.connection_string` as part of its fallback logic when naming inferred databases (eg. where a client span is talking to a non-instrumented database system). As @lmolkova suggested, we should be able to use other fields (like `db.name` and `db.system`) to infer the name/type, but we do use it as a fallback when the others aren't present.

**Comment by trask** [comment]
@breedx-splk we can add a flag in Java instrumentation to keep around `db.connection_string` for a while if you need a transition period

**Comment by breedx-splk** [comment]
> @breedx-splk we can add a flag in Java instrumentation to keep around `db.connection_string` for a while if you need a transition period

Thanks, I appreciate that offer @trask. I'm checking with our internal folks to see what they think. 

Another option too is to make it configurable, default it to false (excluded), and allow a distro to override the default (that way we can manage the time we need to keep it around while vanilla can remain spec compliant).
