### ISSUE TITLE
`db.mssql.instance_name` vs `db.instance.id` and `server.port`

### ISSUE THREAD

**Issue by lmolkova** [open-telemetry/semantic-conventions#727]
Attribute | Type | Description | Examples
-- | -- | -- | --
`db.mssql.instance_name` | string | The Microsoft SQL Server instance name connecting to. This name is used to determine the port of a named instance. [1] | `MSSQLSERVER`

**[1]: If setting a `db.mssql.instance_name`, `server.port` is no longer required (but still recommended if non-standard).**

Issues:

1. It sounds like generic `db.instance.id` can be used. Related #725
2. Based on [SQL Server docs](https://learn.microsoft.com/en-us/sql/database-engine/configure-windows/configure-a-server-to-listen-on-a-specific-tcp-port?view=sql-server-ver16), ports are dynamic, so `server.port` is not known at all and connection is made against [hostname + instance name](Based on [named instances docs](https://learn.microsoft.com/en-us/sql/database-engine/configure-windows/database-engine-instances-sql-server?view=sql-server-ver16#instances)). So probably `network.address.port` should be use here instead. Related: #690

**Comment by Oberon00** [comment]
See https://github.com/open-telemetry/semantic-conventions/issues/725#issuecomment-1935468292:

> AFAIK, the MS SQL instance does not match your proposed description of db.instance.id. It seems to be a quite special concept, I wonder if you will find anything equivalent in any other db.
MS SQL instances are not members of a cluster. Depending on which "instance" you connect to, you will have different databases. This instance concept seems to allow running logically distinct DBs on the same hostname, so it's rather the opposite of clustering.
>
> https://learn.microsoft.com/en-us/sql/database-engine/configure-windows/database-engine-instances-sql-server?view=sql-server-ver16

**Comment by trask** [comment]
@lmolkova is this resolved by #911?

**Comment by lmolkova** [comment]
> @lmolkova is this resolved by #911?

yes, closing this one.

The tl;dr: `db.mssql.instance_name` is now part of `db.namespace` following {instance_name.database name} pattern. Default instance name is not populated.
