### ISSUE TITLE
Move metric definitions to YAML - System Metrics

### ISSUE THREAD

**Issue by joaopgrassi** [open-telemetry/semantic-conventions#73]
Move the metric definitions text from `system-metrics.md` to a respective `system-metrics.yaml` and re-generate the markdown tables.

**Comment by frzifus** [comment]
I can work on this

**Comment by joaopgrassi** [comment]
Hi @frzifus! I sent a PR for it some time ago https://github.com/open-telemetry/semantic-conventions/pull/89. I think what is missing is define/agree on the attribute namespaces and how we will communicate the probably breaking change in them. If you have time feel free to take over!
