### ISSUE TITLE
Messaging span names and metrics: should we lowercase destination name?

### ISSUE THREAD

**Issue by lmolkova** [open-telemetry/semantic-conventions#744]
we use `messaging.destintation.name` on metrics and in the span name, but we don't specify the case.

In case of case-insensitive brokers it could mean we'll have  multiple representations of the same value in the span names or on the metric dimensions.

However, if broker is case-insensitive the original casing could be important.

**Comment by pyohannes** [comment]
> However, if broker is case-insensitive the original casing could be important.

Both Kafka topic names and RabbitMQ routing keys are case sensitive. Lower-casing of destination names could be a requirement that only system-specific messaging conventions can make.

**Comment by pyohannes** [comment]
Closed based on information in the previous comment.
