### ISSUE TITLE
required system uptime metric to the semantic conventions that will describe the system uptime. 

### ISSUE THREAD

**Issue by bhupenbisht** [open-telemetry/semantic-conventions#747]
We are not getting system uptime for server(windows,linux) hostmetrics. as a metric that measures the uptime of the system. For host observability purpose uptime should be scrap.

**Comment by joaopgrassi** [comment]
Hi @bhupenbisht I think this is a duplicate of #648. Please take a look, and if yes I will close this.

**Comment by bhupenbisht** [comment]
Hi @joaopgrassi yes.. its same requirement. Could you please confirm if this is available..?

**Comment by joaopgrassi** [comment]
Close as dup of #648
