### ISSUE TITLE
DB: deprecate `db.jdbc.driver_classname` attribute

### ISSUE THREAD

**Issue by lmolkova** [open-telemetry/semantic-conventions#782]
Java does not capture it - https://github.com/open-telemetry/semantic-conventions/pull/780#discussion_r1506194080

**Comment by lmolkova** [comment]
@arminru brought up a great point that we might eventually want to bring the driver back. We should still be able to do so by un-deprecating the attribute.
The other alternative would be to come up with language-agnostic attribute (DB driver/provider concept is not specific to Java) such as `db.driver.class_name` or `db.client.provider.name`.

**Comment by trask** [comment]
I support deprecating it for now and we can add some way to capture it back once demand and usecases emerge
