### ISSUE TITLE
Messaging metrics: clarify it's about client-side

### ISSUE THREAD

**Issue by lmolkova** [open-telemetry/semantic-conventions#795]
Looking at https://github.com/open-telemetry/semantic-conventions/blob/main/docs/messaging/messaging-metrics.md, it's not immediately obvious they cover client-side only.

We should document it in the title, but also update metric names to emphasize it.

We should consider `messaging.producer.publish.duration` and  `messaging.consumer.process|receive.duration`.

Besides being more descriptive, it would leave space for broker metrics (if they ever come to messaging namespace).

**Comment by pyohannes** [comment]
This is a good idea. It also keeps consistency with HTTP, RPC, and databases, where the pattern always is `<area>.<span-kind>`.

**Comment by lmolkova** [comment]
Closing in favor of #937 which seems to be broader and has more context
