### ISSUE TITLE
Messaging: generalize common attributes to future-proof metrics

### ISSUE THREAD

**Issue by lmolkova** [open-telemetry/semantic-conventions#797]
See https://github.com/open-telemetry/semantic-conventions/issues/760#issuecomment-1982246592

One of the options to minimize future breaking for generic metrics when specific messaging extension decides to add an attribute, is to generalize a few common attributes.

While in general this approach is problematic, there are several common patterns we should consider: 
- Partition Id. Partitioning is common technique used by [Kafka](https://developer.confluent.io/courses/apache-kafka/partitions/), [Azure EventHubs](https://learn.microsoft.com/en-us/azure/event-hubs/event-hubs-features#partitions), [Apache Pulsar](https://pulsar.apache.org/docs/3.1.x/concepts-messaging/#partitioned-topics), [GCP PubSub](https://cloud.google.com/pubsub/lite/docs/topics#provisioning_capacity). Partitioning is the first-class citizen exposed through public API and important for observability. Things like throughput, consumer lag, other important properties can be quite different per partition.
- Consumer group. Another common approach to have multiple groups of consumers that process different positions in the topic and synchronize checkpoint/loadbalance within the group. Supported by [Kafka](https://docs.confluent.io/platform/current/clients/consumer.html#consumer-groups), Azure [EventHubs](https://learn.microsoft.com/en-us/azure/event-hubs/event-hubs-features#consumer-groups),  [rocketmq](https://rocketmq.apache.org/docs/domainModel/07consumergroup), [NATS](https://docs.nats.io/nats-concepts/core-nats/queue)
- A very similar thing called subscription (ability to fan-out messages to multiple groups of subscribers) exists for [GCP PubSub](https://cloud.google.com/pubsub/docs/subscription-overview), [Azure ServiceBus](https://learn.microsoft.com/en-us/azure/service-bus-messaging/service-bus-queues-topics-subscriptions#topics-and-subscriptions), [Apache Pulsar](https://pulsar.apache.org/docs/next/client-libraries-consumers/)
- Delivery/commit mode (auto-commit). #751 for the details on Kafka and RabbitMQ, aka [Receive-And-Delete on Azure Service Bus](https://learn.microsoft.com/en-us/azure/service-bus-messaging/message-transfers-locks-settlement#receiveanddelete). Not clear if it's useful on metrics

**Comment by pyohannes** [comment]
Partitions and consumer groups are concepts usually associated with systems that do checkpoint-based settlement (instead of individual message settlement).

Currently, all attributes we've defined for generic metrics apply to all messaging systems independently of the settlement style.

While I'm all in favor of generalizing attribute naming (e. g. to `messaging.destination.partition.id`), let's further discuss adding such attributes to generic metrics. I'm not yet sure if we should attributes that are of no use at all to certain systems.

**Comment by pyohannes** [comment]
> I wonder if we can entertain an idea of messaging.destination.path that would fully identify destination from the consumer side and include subscription name, consumer group, partition or anything else.

There are two things that should be separated:
1. A consistent definition of a destination that can apply to both producers and consumers. For checkpoint-based systems, this would involve a destination name (a topic name) and a server address.
2. A complete definition of a destination for consumers. This involves the destination name (topic name), the server address, the partition id, and a consumer group.

We should be able to separately identify both.
