### ISSUE TITLE
Add way to programmatically identify experimental vs stable semantic conventions

### ISSUE THREAD

**Issue by dyladan** [open-telemetry/semantic-conventions#81]
In JS we're currently updating our SemConv package to use the new repository for code generation. So far everything has been experimental so we can treat everything the same, but now that the HTTP semconv (and others coming soon) is nearing stability we would like to be able to provide a separate library for stable semconv. With the current repository layout there is no way to identify which attributes are considered stable and which are not.

**Comment by Oberon00** [comment]
What do you mean by "programmatically"? The stability attribute ("deprecated" |  "experimental" |  "stable") is part of the YAML model and can be queried in code generators (though I don't know off the top of my head if it is correctly set)

**Comment by dyladan** [comment]
Ah I looked at the yaml and didn't see anything like that. If we have that it is exactly what I wanted.
