### ISSUE TITLE
`db|messaging|*.system` describes the client library but not necessarily the underlying system

### ISSUE THREAD

**Issue by lmolkova** [open-telemetry/semantic-conventions#813]
Usually client library is specific to a certain DB/broker/etc, but it's also common to support non-native libs/backends. Examples:
- Azure Event Hubs broker [supports Kafka client libraries](https://learn.microsoft.com/en-us/azure/event-hubs/azure-event-hubs-kafka-overview)
- Azure CosmosDB [can be used with MongoDB libs](https://www.mongodb.com/docs/drivers/cosmosdb-support/)
- Several LLM solutions provide OpenAI-compatible REST APIs ([1](https://aws.amazon.com/marketplace/pp/prodview-wutjvjmubfkk6#:~:text=OpenAI%20API%20Compatibility%3A%20Our%20Mistral,AI%20experience%20intuitive%20and%20consistent.), [2](https://ollama.com/blog/openai-compatibility), [3](https://github.com/tensorchord/modelz-llm)) and are used via OpenAI SDKs

So `*.system` might not be the perfect word since the attribute value describes the client lib only.
Keeping `system` might also be good enough, but we need to clarify the attribute definition.

**Comment by pyohannes** [comment]
The `*.system` attributes describes the system that the client library is a part of (for example if a span is created by JMS this should result in `messaging.system=jms`, if the underlying Kafka library creates a span, this should be `messaging.system=kafka`).

**Comment by pyohannes** [comment]
One other important point worth mentioning here is, that the system specified in e. g. `messaging.system` serves as a reference frame for other `messaging.*` attributes.

For example, if I'm using RabbitMQ via MassTransit in .NET, then for telemetry that has `messaging.system=rabbitmq` set, the value in `messaging.message.id` should be the RabbitMQ message id. For telemetry that has `messaging.system=masstransit` set, the value in `messaging.message.id` should be the MassTransit message id (which differs from the RabbitMQ message id).

**Comment by trask** [comment]
> Keeping `system` might also be good enough

👍 (mostly because I can't think of something better though)

> we need to clarify the attribute definition

👍

**Comment by jack-berg** [comment]
> So *.system might not be the perfect word since the attribute value describes the client lib only.

It would be a shame if `db.system` was a descriptor of the client library and not the target system, since we already capture information about the client library in instrumentation scope.

**Comment by trask** [comment]
maybe it's more like a descriptor for the client protocol?

**Comment by lmolkova** [comment]
I'd say `*.system` describes the client library understanding of what it communicates with. 

I also don't think there is a duplication between instrumentation scope name and system. E.g. `lettuce` does not adequately describe that telemetry conforms to databse semconv with redis extension.

**Comment by trask** [comment]
> I also don't think there is a duplication between instrumentation scope name and system. E.g. lettuce does not adequately describe that telemetry conforms to databse semconv with redis extension.

👍
