### ISSUE TITLE
Mark HTTP semantic conventions as stable in the YAML definitions

### ISSUE THREAD

**Issue by arminru** [open-telemetry/semantic-conventions#82]
Our semantic convention tooling defines a property called `stability` for semantic conventions.
Once we finally stabilize our HTTP conventions, the YAML files should be updated to set this property to `stable`.

See https://github.com/open-telemetry/build-tools/blob/main/semantic-conventions/syntax.md#syntax for details.

**Comment by jsuereth** [comment]
Is this a blocker for our release?

**Comment by arminru** [comment]
@jsuereth It's a bit of a chicken and egg thing. Ideally we'd just mark both stable in an atomic operation but otherwise either order should be fine as well. If both happens in the same semconv release it will be consistent enough for sure.

Since the upcoming semconv release doesn't mark HTTP stable quite yet it's not a blocker for that release anyway though.
