### ISSUE TITLE
Move metric requirement level definition from spec to semconv repo

### ISSUE THREAD

**Issue by lmolkova** [open-telemetry/semantic-conventions#822]
Metrics requirement levels makes sense in a scope of semantic convention and the corresponding doc https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/metrics/metric-requirement-level.md should belong in this repo.

Note: attribute requirement levels live in the semconv - https://github.com/open-telemetry/semantic-conventions/blob/0220d78f63e088a50fe8e4f827b97a28a42aeb23/docs/general/attribute-requirement-level.md

**Comment by joaopgrassi** [comment]
I guess we will have to modify all conventions after the move, but that's doable with a find/replace all :). I can fix it if you are not already on it.

**Comment by lmolkova** [comment]
I didn't get to it, so please go ahead if you can. Thanks!
