### ISSUE TITLE
Add  CI Attributes to Sem Conv

### ISSUE THREAD

**Issue by adrielp** [open-telemetry/semantic-conventions#832]
# Overvew 

The CI/CD Working Group is looking to add semantic conventions for CI and CD Observability. This task serves to add the basic core attributes for continuous integration (builds).

**Comment by arminru** [comment]
@open-telemetry/semconv-cicd-approvers Can this be resolved now that https://github.com/open-telemetry/semantic-conventions/pull/1075 was merged, or is this issue here intended to have a broader scope?

**Comment by adrielp** [comment]
@arminru - I'll make a couple adjustments and clean up these now that that's been merged in. Thanks for checking!

**Comment by adrielp** [comment]
Resolved now that #1075 was merged.
