### ISSUE TITLE
Add deployment attributes to SemConv

### ISSUE THREAD

**Issue by adrielp** [open-telemetry/semantic-conventions#833]
# Overvew 

The CI/CD Working Group is looking to add semantic conventions for CI and CD Observability. This task serves to add the basic core attributes for continuous deployment.

**Comment by arminru** [comment]
@open-telemetry/semconv-cicd-approvers Can this be resolved now that https://github.com/open-telemetry/semantic-conventions/pull/1075 was merged, or is this issue here intended to have a broader scope?

**Comment by adrielp** [comment]
Resolved through #1075 was merged
