### ISSUE TITLE
Add sustainability metrics and attributes to semantic conventions for hardware metrics

### ISSUE THREAD

**Issue by bertysentry** [open-telemetry/semantic-conventions#835]
## Use Case

We need to be able to report the carbon footprint of servers, network, storage, applications, and services. To allow that across the entire infrastructure, semantic conventions are required, starting with the underlying physical infrastructure.

## Specifications

In addition to `hw.power` and `hw.energy`, add metrics to semantic conventions for hardware metrics, like:

* `hw.abiotic_depletion_potential`
* `hw.product_carbon_footprint`

Define a *Site* entity, i.e. a physical location with specific properties that can be measured with metrics like:

* `hw.site.pue` ([more](https://knowledge.sdialliance.org/data-center-metrics#903dbdc8aae84211aa42aa33c625ab7e))
* `hw.site.itue`, `hw.site.tue` ([more](https://knowledge.sdialliance.org/data-center-metrics#e6bcce2b25fb4671a51086dc1eee1695))
* `hw.site.cue` ([more](https://knowledge.sdialliance.org/data-center-metrics#1ae20a03c3f24f6c8558504fdcc6a4af))
* `hw.site.wue`
* `hw.site.ere`, `hw.site.erf` ([more](https://knowledge.sdialliance.org/data-center-metrics#f3b2ee7b318a41a39d16a3cabe2b3ebf))
* `hw.site.ref`, `hw.site.oef` ([more](https://knowledge.sdialliance.org/data-center-metrics#284afeeab1cd474bb0a84dbad125d687))
* `hw.site.cer` ([more](https://knowledge.sdialliance.org/data-center-metrics#fe1467211e0b4f5484f8eae368b4a0a1))
* `hw.site.electricity_cost`
* `hw.site.carbon_intensity`

## Additional context

More examples and links can be found in various places, but [Green Software Foundation's Awesome Green Software](https://github.com/Green-Software-Foundation/awesome-green-software) is a good reference to start with, as well as its [Hardware Efficiency](https://learn.greensoftware.foundation/hardware-efficiency) page.

**Comment by nikimanoledaki** [comment]
As per @jpkrohling's & @pyohannes's comments:
> In any case: it looks like this needs a working group, and we might not have enough experts in the community to confidently drive this. I'd recommend gathering people who are passionate about this topic to collaborate as part of a WG.
> 
> A somewhat old document by @tedsuo describes how a new WG around semantic conventions can be formed: https://docs.google.com/document/d/1ghvajKaipiNZso3fDtyNxU7x1zx0_Eyd02OGpMGEpLE/edit . I'm not sure this was ever formalized in the full context of that doc, but I know the project management parts are described here: https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/project-management.md

> * Writing a project tracking issue (see [here](https://github.com/open-telemetry/opentelemetry-specification/issues?q=is%3Aissue+is%3Aopen+project+tracking) and [here](https://github.com/open-telemetry/community/issues?q=is%3Aissue+is%3Aopen+project+tracking) for examples).
> * Join the [semantic conventions SIG meeting](https://docs.google.com/document/d/10xG7DNKWRhxNmFGt3yYd3980a9uwS8lMl2LvQL3VNK8/edit#heading=h.ylazl6464n0c) and talk about your intentions. This might be a first step to find possible sponsors from OTel side.

Would anyone like to volunteer to kickoff the WG creation process by filing a [Project Tracking Issue](https://github.com/open-telemetry/opentelemetry-specification/issues/new?assignees=&labels=spec%3Aproject-tracking&template=project.md), please?

**Comment by Spazzy757** [comment]
Hi,

Ive startyed this issue: https://github.com/open-telemetry/opentelemetry-specification/issues/3958

Still fleshing out the details, but happy to push this. Im also getting access to GSF slack to see if we can get some input there

**Comment by danielgblanco** [comment]
Considering we have the project aforementioned and the following project board

https://github.com/orgs/open-telemetry/projects/93/views/1

Does it still make sense to keep this issue active?

For anyone else seeing this, please follow the info in https://github.com/open-telemetry/community?tab=readme-ov-file#special-interest-groups if you'd like to participate in this SIG!

**Comment by bertysentry** [comment]
We can close this issue. Thank you all for the interest and for the work that will be done to achieve this! 😊
