### ISSUE TITLE
Consider merging `*.cpu.state` metric attributes

### ISSUE THREAD

**Issue by ChrsMark** [open-telemetry/semantic-conventions#840]
### Area(s)

area:container
area:system
area:process

### Is your change request related to a problem? Please describe.

At the moment we have 3 different metric attributes representing the `cpu.state`:

- [`system.cpu.state`](https://github.com/open-telemetry/semantic-conventions/blob/4368358cdcdd78f37291317a31cbc413080738ec/model/metrics/system-metrics.yaml#L20)
- [`process.cpu.state`](https://github.com/open-telemetry/semantic-conventions/blob/4368358cdcdd78f37291317a31cbc413080738ec/model/metrics/process-metrics.yaml#L7)
- [`container.cpu.state`](https://github.com/open-telemetry/semantic-conventions/pull/282#discussion_r1528808420)

Based on the global flat registry idea it would be nice if we had one single definition for this attribute and then be able to re-use it in the various namespaces.

### Describe the solution you'd like

As it is explained at https://github.com/open-telemetry/semantic-conventions/pull/681#discussion_r1511310673 we could consider merging into one single one called `cpu.state` similar to the [`disk.io.direction`](https://github.com/open-telemetry/semantic-conventions/blob/4368358cdcdd78f37291317a31cbc413080738ec/model/registry/disk.yaml#L8) and [`network.io.direction`](https://github.com/open-telemetry/semantic-conventions/blob/4368358cdcdd78f37291317a31cbc413080738ec/model/registry/network.yaml#L191).

### Describe alternatives you've considered

Maybe the `embed` concept would be sth to think of here: https://github.com/open-telemetry/build-tools/issues/240

cc @open-telemetry/semconv-system-approvers @open-telemetry/semconv-container-approvers @open-telemetry/semconv-k8s-approvers

**Comment by ChrsMark** [comment]
So to summarize the situation here, we have the following:

## System Metrics

Values for [`system.cpu.state`](https://github.com/open-telemetry/semantic-conventions/blob/4368358cdcdd78f37291317a31cbc413080738ec/model/metrics/system-metrics.yaml#L20):
- `user`
- `system`
- `nice`
- `idle`
- `iowait`
- `interrupt`
- `steal`

## Process Metrics

Values for [`process.cpu.state`](https://github.com/open-telemetry/semantic-conventions/blob/4368358cdcdd78f37291317a31cbc413080738ec/model/metrics/process-metrics.yaml#L7):
- `user`
- `system`
- `wait`

## Container Metrics

Values for [`container.cpu.state`](https://github.com/open-telemetry/semantic-conventions/blob/d8d0fb113f9cb986e4004395a30eb29c648a5376/model/registry/container.yaml#L98):
- `user`
- `system`
- `kernel`


Based on @braydonk's [comment](https://github.com/open-telemetry/semantic-conventions/pull/681#discussion_r1511310673) we can change the `wait` value of the `process.cpu.state` to `idle` and hence the `process.cpu.state` will be a subset of the `system.cpu.state`. Then we can use the superset for both.

Then the only difference with the `container.cpu.state` is the `kernel` value.
Checking the [`dockerstatsreceiver`](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/b25b78a1a7b1228414249265c08178ca40ef0cf9/receiver/dockerstatsreceiver/receiver.go#L266) implementation, this value comes directly from the [Docker API](https://pkg.go.dev/github.com/docker/docker/api/types#CPUUsage). For now I guess we should use it as is unless we find way to properly correlate it with rest of set's values. @jamesmoessis  feel free to comment here if you have more information.

My first proposal would be to unify the attribute to `cpu.state` with possible values the being following `[user, system, nice, idle, iowait, interrupt, steal, kernel]`.

What do you @open-telemetry/semconv-system-approvers think about this?

**Comment by AlexanderWert** [comment]
I like the proposal, it simplifies things.

**Comment by ishleenk17** [comment]
@ChrsMark : Mostly for system metrics, we consider the states mentioned [here](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/receiver/hostmetricsreceiver/internal/scraper/cpuscraper/documentation.md#systemcpuutilization). It has 1 extra  state `softirq`, which I don't see in the [code](https://github.com/open-telemetry/semantic-conventions/blob/4368358cdcdd78f37291317a31cbc413080738ec/model/metrics/system-metrics.yaml#L20) you pointed to. 
Just a thought, if we want to consider that as another member of the state as well.

**Comment by joaopgrassi** [comment]
Removing the triage label, as this sounds like a good plan. Unifying them makes sense to me.

**Comment by mx-psi** [comment]
I am in favor of this.

> IThere's an additional state softirq, which I didn't find in the [code](https://github.com/open-telemetry/semantic-conventions/blob/4368358cdcdd78f37291317a31cbc413080738ec/model/metrics/system-metrics.yaml#L20) you referenced.

@ishleenk17 I think this is Linux-specific, so it should go into its own separate metric like we did on #323

**Comment by trisch-me** [comment]
@ChrsMark it's not possible yet but we are discussinga few weeks ago this option, one similar reference would be https://github.com/open-telemetry/build-tools/issues/192 to exend enum from some `base` one, but option to use specific fields will be most probably also implemented
