### ISSUE TITLE
Rename `db.operation` to `db.operation.name` for future proofing

### ISSUE THREAD

**Issue by trask** [open-telemetry/semantic-conventions#884]
This will give us the chance to add more attributes under the `db.operation.*` namespace post-stabilization.

In particular, @lmolkova's https://github.com/open-telemetry/semantic-conventions/pull/875#issuecomment-2038034089:

> I think we might entertain the idea of `db.operation.duration` metric (and it might still be an open question for messaging metrics since operation list is an open set).
>
> In case of databases, we have a precedent when [CosmosDB](https://github.com/open-telemetry/semantic-conventions/blob/main/docs/database/cosmosdb.md#semantic-conventions-for-microsoft-cosmos-db) records operation name (e.g. `ReadItems`)  along with `db.cosmosdb.operation_type` (e.g. `Read`). We might want to generalize at some point.
If we translated it to messaging, we'd do something like `messaging.operation.type = settle, messaging.operation.name = ack`.

and https://github.com/open-telemetry/semantic-conventions/pull/875#issuecomment-2038050927:

> Also, graphql has `operation.name` and `operation.type` - https://github.com/open-telemetry/semantic-conventions/blob/main/docs/graphql/graphql-spans.md

**Comment by arminru** [comment]
Done in #875.
