### ISSUE TITLE
Consider ResourceAttributes add k8s.node.ip and k8s.pod.ip

### ISSUE THREAD

**Issue by zhangjiabin1010** [open-telemetry/semantic-conventions#918]
### Area(s)

area:k8s

### Is your change request related to a problem? Please describe.

ResourceAttributes add k8s.node.ip and k8s.pod.ip  Quickly locate the host

### Describe the solution you'd like

ResourceAttributes add k8s.node.ip and k8s.pod.ip  Quickly locate the host
[Add node and pod ip env vars automatically](https://github.com/open-telemetry/opentelemetry-operator/pull/2769#issue-2195411099)
Add node IP and pod IP to env vars automatically.

**Comment by joaopgrassi** [comment]
We have a new issue for this, so I will close this as duplicated: https://github.com/open-telemetry/semantic-conventions/issues/1160
