### ISSUE TITLE
Log errors

### ISSUE THREAD

**Issue by dmathieu** [open-telemetry/semantic-conventions#921]
### Area(s)

area:error

### Is your change request related to a problem? Please describe.

Logs have semantic conventions for exceptions, but not all errors are exceptions (some languages such as Go don't even have the notion of exception).

### Describe the solution you'd like

Introduce the `error` namespace for logs, and add the field `error.message` to that namespace.

### Describe alternatives you've considered

We could also not introduce a new namespace, and document that non-exception errors should be treated as exceptions.

### Additional context

* [Log Exceptions](https://github.com/open-telemetry/semantic-conventions/blob/main/docs/exceptions/exceptions-logs.md)
* [Error namespace](https://github.com/open-telemetry/semantic-conventions/blob/main/docs/attributes-registry/error.md)

**Comment by pyohannes** [comment]
There's been some related discussions in https://github.com/open-telemetry/opentelemetry-specification/issues/3198.

I think it was the discussion in this issue that resulted in the introduction of the [`error` namespace](https://github.com/open-telemetry/semantic-conventions/blob/main/docs/attributes-registry/error.md).

Also, in this issue there were some interesting discussions about the fact that the term "error" corresponds to the span status in tracing, but to the severity in logging. For spans, it seemed feasible to use the status description for capturing error messages, however, it wasn't clear how this should translate to other signals.

**Comment by joaopgrassi** [comment]
I wonder if discussions about this should be kept in the spec issue or here. Seems it goes beyond semantic conventions and affects other areas as well.

**Comment by dmathieu** [comment]
With `exception` being stabilized, I suppose a rename of `exception` into `error` is not possible.
The specification above did mention having both exceptions and errors though.

I'm also happy opening a spec issue if that'd be a better place.

**Comment by pellared** [comment]
@dmathieu, with https://github.com/open-telemetry/opentelemetry-go/blob/e3892f062f3f92cce9b2a61478c46babe6f6331d/sdk/trace/span.go#L448-L460 I think we are fine using `exception.type` and `exception.message` and follow https://github.com/open-telemetry/semantic-conventions/blob/main/docs/exceptions/exceptions-logs.md in Log Bridges. WDYT?

**Comment by dmathieu** [comment]
Yes, that's the alternative suggested in the issue description. I'm fine going with that alternative.

**Comment by dmathieu** [comment]
Closing per the last 2 comments.
