### ISSUE TITLE
Rename `messaging.client_id` to `messaging.client.id`

### ISSUE THREAD

**Issue by pyohannes** [open-telemetry/semantic-conventions#935]
The .NET Kafka client supports both a [client id and a client name](https://docs.confluent.io/platform/current/clients/confluent-kafka-dotnet/_site/api/Confluent.Kafka.IClient.html#Confluent_Kafka_IClient_Name).

It seems to be a general possibility that one wants to capture more client related information besides the id. Making `messaging.client` a dedicated namespace would enable this, without loosing current functionality. There could be:
* `messaging.client.id` (renamed from `messaging.client_id`)
* `messaging.client.name`
* Other client related attributes.

**Comment by lachmatt** [comment]
Some additional information.
Default value for `ClientId` for `Confluent.Kafka` .NET client is `rdkafka`. Docs for the library mark this setting as of [low importance](https://docs.confluent.io/platform/current/clients/confluent-kafka-dotnet/_site/api/Confluent.Kafka.ClientConfig.html#Confluent_Kafka_ClientConfig_ClientId) (I assume it might often be left unset).
Messaging semantic conventions [describe](https://github.com/open-telemetry/semantic-conventions/blob/b77c881ad68dca7bb7af2c97899a0ef64357c47c/docs/messaging/messaging-spans.md?plain=1#L298) `messaging.client.id` attribute as an unique identifier for the client. 
Current [recommendation](https://github.com/open-telemetry/semantic-conventions/blob/main/docs/messaging/kafka.md?plain=1#L45) in kafka specific semantic conventions is to use client id value for `messaging.client.id`.
I assume, considering above, that this value will often not be unique.
At the same time, [client name](https://docs.confluent.io/platform/current/clients/confluent-kafka-dotnet/_site/api/Confluent.Kafka.IClient.html#Confluent_Kafka_IClient_Name) is unique across all the client instances in a given application.
