### ISSUE TITLE
Decide on which `db.system` values to mark stable as part of initial db semconv stability

### ISSUE THREAD

**Issue by trask** [open-telemetry/semantic-conventions#965]
Tracking / blocking issue for initial database semconv stability.

**Comment by trask** [comment]
Proposal, factoring in the expertise we have within the database working group:

* `sql`
* `mssql`
* `cosmosdb`
* `elasticsearch`

Others that would be nice, based on popularity:

* `redis`
* `mongodb`

**Comment by trask** [comment]
I suggest we not include `hbase` in the initial stability, as it will be good to sync with hbase native instrumentation prior to stabilizing anything related to `hbase` (see #742)

**Comment by trask** [comment]
> * `sql`

there's no `db.system` constant for `sql`, should we remove the [sql.md](https://github.com/open-telemetry/semantic-conventions/blob/main/docs/database/sql.md) page?

but then what to do since there's no `oracle`, `postgresql` pages?

==> keep `sql` page to document any `db.system` that implement `sql`

**Comment by trask** [comment]
what about picking a timeseries database and a vector database?

**Comment by gregkalapos** [comment]
WG Meeting:
From OTel community day: Regdis and Postres conver a lot - should be marked as stable.
