### ISSUE TITLE
[CI] All PRs fail on docfx check

### ISSUE THREAD

**Issue by AlexanderWert** [open-telemetry/semantic-conventions#987]
### What happened?

PR builds fail on the docfx job (even PRs that succeeded before, if rerunning that job), with the following error message:
<img width="1490" alt="image" src="https://github.com/open-telemetry/semantic-conventions/assets/866830/f9326628-6a34-4385-ac10-1373a1d316ea">

Something is wrong with the installation step of docfx.

### Semantic convention version

N/A

**Comment by gregkalapos** [comment]
It seems this step fetches docfx v. 3.0 from a custom NuGet feed. V3 has never been publically released, on [public NuGet](https://www.nuget.org/packages/docfx) the latest version is v2.76.0. It seems now there is nothing behind this custom NuGet feed from `https://docfx.pkgs.visualstudio.com/docfx/`. They have a [v3 branch](https://github.com/dotnet/docfx/tree/v3) (last commit 2 years ago), I suspect it's a build from that branch. 

Here is a super old discussion about v3 release: https://github.com/dotnet/docfx/issues/7050.

The step runs `docfx build --dry-run`,  which doesn't seem to be present in `2.x`, only in `3.x`.

**Comment by lmolkova** [comment]
FYI: https://github.com/dotnet/docfx/issues/9901

**Comment by lmolkova** [comment]
Thanks to @jsuereth docfx check is not required and we can merge PRs despite it showing errors until we figure out what to do with it.
