### ISSUE TITLE
Add Node.js runtime metrics specific semantic conventions

### ISSUE THREAD

**Issue by maryliag** [open-telemetry/semantic-conventions#990]
### Area(s)

area:nodejs

### Is your change request related to a problem? Please describe.

Currently, only JVM have detailed semantic conventions for its metrics. Other languages would also required, such as Node.js

### Describe the solution you'd like

Addition of Node.js runtime metric conventions

**Comment by joaopgrassi** [comment]
@maryliag I guess we can close this issue, given both PRs got merged?

**Comment by maryliag** [comment]
yes, thank you!
