### ISSUE TITLE
`make table-generation` is broken on Windows (Git Bash) after the switch over to weaver

### ISSUE THREAD

**Issue by trask** [open-telemetry/semantic-conventions#994]
### Area(s)

area:other

## Steps to Reproduce (if any)

Run `make table-generation` on Windows using Git Bash

## Expected Result

Success 😄

## Actual Result

```
✖ IO error for operation on C:/Program Files/Git/source: No such file or directory (os error 2)
make: *** [Makefile:98: table-generation] Error 1
```

### Semantic convention version

main

**Comment by joaopgrassi** [comment]
Hum it used to work before? I guess it's something related to how Git Bash interprets the paths, maybe it messes it up between Unix/Windows 🤔

**Comment by joaopgrassi** [comment]
I set this var in the command `MSYS_NO_PATHCONV=1` as per this old discussion https://github.com/docker-archive/toolbox/issues/673 and it worked. Also seems to not change anything for those running on Linux/MacOS. I can send a PR

**Comment by jsuereth** [comment]
I'm investigating.  This wasn't broken for me.

**Comment by jsuereth** [comment]
So - I think we need more information about your setup.  I've been using WSL.

A few things to confirm:

1. Can you run `docker pull otel/weaver:latest`? Unfortunately, we're using the latest tag right now, but this is fixable.
2. Are you running `make` from the root of the semconv folder?  It appears that windows is trying to read `C:/Program Files/Git/source`.  However, for the docker image, we're trying to mount `{semconv_root}/model` as `/source`.  I think @joaopgrassi may be right that there's some kind of directory conversion happening in your environment that's unwanted for the "docker" side of the path.
